//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U8;
use carbon_core::graphql::primitives::U32;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "PlayerCrewRecord")]
pub struct PlayerCrewRecordGraphQL {
    pub account_metadata: crate::accounts::graphql::AccountMetadataGraphQL,
    pub version: U8,
    pub player_profile: Pubkey,
    pub crew_config: Pubkey,
    pub game_id: Pubkey,
    pub count: U32,
    pub bump: U8,
}

impl TryFrom<crate::accounts::postgres::PlayerCrewRecordRow> for PlayerCrewRecordGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::accounts::postgres::PlayerCrewRecordRow) -> Result<Self, Self::Error> {
        Ok(Self {
            account_metadata: row.account_metadata.into(),
            version: carbon_core::graphql::primitives::U8((*row.version) as u8),
            player_profile: carbon_core::graphql::primitives::Pubkey(row.player_profile.0),
            crew_config: carbon_core::graphql::primitives::Pubkey(row.crew_config.0),
            game_id: carbon_core::graphql::primitives::Pubkey(row.game_id.0),
            count: carbon_core::graphql::primitives::U32((*row.count) as u32),
            bump: carbon_core::graphql::primitives::U8((*row.bump) as u8),
        })
    }
}
