//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::I64;
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U8;
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "Starbase")]
pub struct StarbaseGraphQL {
    pub account_metadata: crate::accounts::graphql::AccountMetadataGraphQL,
    pub version: U8,
    pub game_id: Pubkey,
    pub sector: Vec<I64>,
    pub crafting_facility: Pubkey,
    pub upgrade_facility: Pubkey,
    pub name: Vec<U8>,
    pub sub_coordinates: Vec<I64>,
    pub faction: U8,
    pub bump: U8,
    pub seq_id: i32,
    pub state: U8,
    pub level: U8,
    pub hp: U64,
    pub sp: U64,
    pub sector_ring_available: U8,
    pub upgrade_state: U8,
    pub upgrade_ingredients_checksum: Vec<U8>,
    pub num_upgrade_ingredients: U8,
    pub upkeep_ammo_balance: U64,
    pub upkeep_ammo_last_update: I64,
    pub upkeep_ammo_global_last_update: I64,
    pub upkeep_food_balance: U64,
    pub upkeep_food_last_update: I64,
    pub upkeep_food_global_last_update: I64,
    pub upkeep_toolkit_balance: U64,
    pub upkeep_toolkit_last_update: I64,
    pub upkeep_toolkit_global_last_update: I64,
    pub built_destroyed_timestamp: I64,
    pub shield_break_delay_expires_at: I64,
}

impl TryFrom<crate::accounts::postgres::StarbaseRow> for StarbaseGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::accounts::postgres::StarbaseRow) -> Result<Self, Self::Error> {
        Ok(Self {
            account_metadata: row.account_metadata.into(),
            version: carbon_core::graphql::primitives::U8((*row.version) as u8),
            game_id: carbon_core::graphql::primitives::Pubkey(row.game_id.0),
            sector: row
                .sector
                .into_iter()
                .map(|item| carbon_core::graphql::primitives::I64(item))
                .collect(),
            crafting_facility: carbon_core::graphql::primitives::Pubkey(row.crafting_facility.0),
            upgrade_facility: carbon_core::graphql::primitives::Pubkey(row.upgrade_facility.0),
            name: row
                .name
                .into_iter()
                .map(|item| carbon_core::graphql::primitives::U8(item))
                .collect(),
            sub_coordinates: row
                .sub_coordinates
                .into_iter()
                .map(|item| carbon_core::graphql::primitives::I64(item))
                .collect(),
            faction: carbon_core::graphql::primitives::U8((*row.faction) as u8),
            bump: carbon_core::graphql::primitives::U8((*row.bump) as u8),
            seq_id: (*row.seq_id) as i32,
            state: carbon_core::graphql::primitives::U8((*row.state) as u8),
            level: carbon_core::graphql::primitives::U8((*row.level) as u8),
            hp: carbon_core::graphql::primitives::U64(*row.hp),
            sp: carbon_core::graphql::primitives::U64(*row.sp),
            sector_ring_available: carbon_core::graphql::primitives::U8(
                (*row.sector_ring_available) as u8,
            ),
            upgrade_state: carbon_core::graphql::primitives::U8((*row.upgrade_state) as u8),
            upgrade_ingredients_checksum: row
                .upgrade_ingredients_checksum
                .into_iter()
                .map(|item| carbon_core::graphql::primitives::U8(item))
                .collect(),
            num_upgrade_ingredients: carbon_core::graphql::primitives::U8(
                (*row.num_upgrade_ingredients) as u8,
            ),
            upkeep_ammo_balance: carbon_core::graphql::primitives::U64(*row.upkeep_ammo_balance),
            upkeep_ammo_last_update: carbon_core::graphql::primitives::I64(
                row.upkeep_ammo_last_update,
            ),
            upkeep_ammo_global_last_update: carbon_core::graphql::primitives::I64(
                row.upkeep_ammo_global_last_update,
            ),
            upkeep_food_balance: carbon_core::graphql::primitives::U64(*row.upkeep_food_balance),
            upkeep_food_last_update: carbon_core::graphql::primitives::I64(
                row.upkeep_food_last_update,
            ),
            upkeep_food_global_last_update: carbon_core::graphql::primitives::I64(
                row.upkeep_food_global_last_update,
            ),
            upkeep_toolkit_balance: carbon_core::graphql::primitives::U64(
                *row.upkeep_toolkit_balance,
            ),
            upkeep_toolkit_last_update: carbon_core::graphql::primitives::I64(
                row.upkeep_toolkit_last_update,
            ),
            upkeep_toolkit_global_last_update: carbon_core::graphql::primitives::I64(
                row.upkeep_toolkit_global_last_update,
            ),
            built_destroyed_timestamp: carbon_core::graphql::primitives::I64(
                row.built_destroyed_timestamp,
            ),
            shield_break_delay_expires_at: carbon_core::graphql::primitives::I64(
                row.shield_break_delay_expires_at,
            ),
        })
    }
}
