//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::I64;
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U8;
use carbon_core::graphql::primitives::U32;
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "CombatParticipant")]
pub struct CombatParticipantGraphQL {
    pub fleet_key: Pubkey,
    pub fleet_label: Vec<U8>,
    pub fleet_state: U8,
    pub owner_profile: Pubkey,
    pub player_key: Pubkey,
    pub faction: U8,
    pub public_key: Pubkey,
    pub pre_hp: U32,
    pub pre_sp: U32,
    pub pre_ap: U32,
    pub post_hp: U32,
    pub post_sp: U32,
    pub post_ap: U32,
    pub total_attack_power: U32,
    pub total_defense_power: U32,
    pub agility: U32,
    pub ship_class_counts: Vec<U32>,
    pub position_x: I64,
    pub position_y: I64,
    pub sector_key: Pubkey,
    pub ammo_count: U64,
    pub fuel_count: U64,
    pub combat_xp: U64,
    pub council_rank: i32,
}

impl From<crate::types::CombatParticipant> for CombatParticipantGraphQL {
    fn from(original: crate::types::CombatParticipant) -> Self {
        Self {
            fleet_key: carbon_core::graphql::primitives::Pubkey(original.fleet_key),
            fleet_label: original
                .fleet_label
                .into_iter()
                .map(|item| carbon_core::graphql::primitives::U8(item))
                .collect(),
            fleet_state: carbon_core::graphql::primitives::U8(original.fleet_state),
            owner_profile: carbon_core::graphql::primitives::Pubkey(original.owner_profile),
            player_key: carbon_core::graphql::primitives::Pubkey(original.player_key),
            faction: carbon_core::graphql::primitives::U8(original.faction),
            public_key: carbon_core::graphql::primitives::Pubkey(original.public_key),
            pre_hp: carbon_core::graphql::primitives::U32(original.pre_hp),
            pre_sp: carbon_core::graphql::primitives::U32(original.pre_sp),
            pre_ap: carbon_core::graphql::primitives::U32(original.pre_ap),
            post_hp: carbon_core::graphql::primitives::U32(original.post_hp),
            post_sp: carbon_core::graphql::primitives::U32(original.post_sp),
            post_ap: carbon_core::graphql::primitives::U32(original.post_ap),
            total_attack_power: carbon_core::graphql::primitives::U32(original.total_attack_power),
            total_defense_power: carbon_core::graphql::primitives::U32(
                original.total_defense_power,
            ),
            agility: carbon_core::graphql::primitives::U32(original.agility),
            ship_class_counts: original
                .ship_class_counts
                .into_iter()
                .map(|item| carbon_core::graphql::primitives::U32(item))
                .collect(),
            position_x: carbon_core::graphql::primitives::I64(original.position_x),
            position_y: carbon_core::graphql::primitives::I64(original.position_y),
            sector_key: carbon_core::graphql::primitives::Pubkey(original.sector_key),
            ammo_count: carbon_core::graphql::primitives::U64(original.ammo_count),
            fuel_count: carbon_core::graphql::primitives::U64(original.fuel_count),
            combat_xp: carbon_core::graphql::primitives::U64(original.combat_xp),
            council_rank: original.council_rank as i32,
        }
    }
}
