//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::I64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "DiscoverSectorInput")]
pub struct DiscoverSectorInputGraphQL {
    pub coordinates: Vec<I64>,
    pub key_index: i32,
}

impl From<crate::types::DiscoverSectorInput> for DiscoverSectorInputGraphQL {
    fn from(original: crate::types::DiscoverSectorInput) -> Self {
        Self {
            coordinates: original
                .coordinates
                .into_iter()
                .map(|item| carbon_core::graphql::primitives::I64(item))
                .collect(),
            key_index: original.key_index as i32,
        }
    }
}
