//! This code was AUTOGENERATED using the Codama library.
use crate::types::graphql::FactionsStarbaseLevelInfoGraphQL;
use crate::types::graphql::StarbaseUpkeepLevelsGraphQL;
use carbon_core::graphql::primitives::U32;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "FleetInfo")]
pub struct FleetInfoGraphQL {
    pub starbase_levels: FactionsStarbaseLevelInfoGraphQL,
    pub upkeep: StarbaseUpkeepLevelsGraphQL,
    pub max_fleet_size: U32,
}

impl From<crate::types::FleetInfo> for FleetInfoGraphQL {
    fn from(original: crate::types::FleetInfo) -> Self {
        Self {
            starbase_levels: original.starbase_levels.into(),
            upkeep: original.upkeep.into(),
            max_fleet_size: carbon_core::graphql::primitives::U32(original.max_fleet_size),
        }
    }
}
