//! This code was AUTOGENERATED using the Codama library.
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "ReloadInput")]
pub struct ReloadInputGraphQL {
    pub key_index: i32,
}

impl From<crate::types::ReloadInput> for ReloadInputGraphQL {
    fn from(original: crate::types::ReloadInput) -> Self {
        Self {
            key_index: original.key_index as i32,
        }
    }
}
