//! This code was AUTOGENERATED using the Codama library.
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "RetrieveLootInput")]
pub struct RetrieveLootInputGraphQL {
    pub key_index: i32,
}

impl From<crate::types::RetrieveLootInput> for RetrieveLootInputGraphQL {
    fn from(original: crate::types::RetrieveLootInput) -> Self {
        Self {
            key_index: original.key_index as i32,
        }
    }
}
