//! This code was AUTOGENERATED using the Codama library.
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "ScanForSurveyDataUnitsInput")]
pub struct ScanForSurveyDataUnitsInputGraphQL {
    pub key_index: i32,
}

impl From<crate::types::ScanForSurveyDataUnitsInput> for ScanForSurveyDataUnitsInputGraphQL {
    fn from(original: crate::types::ScanForSurveyDataUnitsInput) -> Self {
        Self {
            key_index: original.key_index as i32,
        }
    }
}
