//! This code was AUTOGENERATED using the Codama library.
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "UpdateResourceInput")]
pub struct UpdateResourceInputGraphQL {
    pub system_richness: Option<i32>,
    pub key_index: i32,
}

impl From<crate::types::UpdateResourceInput> for UpdateResourceInputGraphQL {
    fn from(original: crate::types::UpdateResourceInput) -> Self {
        Self {
            system_richness: original.system_richness.map(|v| v as i32),
            key_index: original.key_index as i32,
        }
    }
}
