//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U32;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "UpdateShipEscrowInput")]
pub struct UpdateShipEscrowInputGraphQL {
    pub ship_escrow_index: U32,
}

impl From<crate::types::UpdateShipEscrowInput> for UpdateShipEscrowInputGraphQL {
    fn from(original: crate::types::UpdateShipEscrowInput) -> Self {
        Self {
            ship_escrow_index: carbon_core::graphql::primitives::U32(original.ship_escrow_index),
        }
    }
}
