//! This code was AUTOGENERATED using the Codama library.
pub mod mint_crew_member_schema;
pub mod redeem_crew_pack_schema;
pub mod register_crew_config_schema;
pub mod register_pack_tiers_schema;
pub mod register_pack_type_schema;
pub mod register_sft_redemption_schema;
pub mod update_pack_tiers_schema;

pub use mint_crew_member_schema::*;
pub use redeem_crew_pack_schema::*;
pub use register_crew_config_schema::*;
pub use register_pack_tiers_schema::*;
pub use register_pack_type_schema::*;
pub use register_sft_redemption_schema::*;
pub use update_pack_tiers_schema::*;

use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "InstructionMetadata")]
pub struct InstructionMetadataGraphQL {
    pub signature: String,
    pub instruction_index: carbon_core::graphql::primitives::U32,
    pub stack_height: carbon_core::graphql::primitives::U32,
    pub slot: Option<carbon_core::graphql::primitives::U64>,
}

impl From<carbon_core::postgres::metadata::InstructionRowMetadata> for InstructionMetadataGraphQL {
    fn from(metadata: carbon_core::postgres::metadata::InstructionRowMetadata) -> Self {
        Self {
            signature: metadata.signature,
            instruction_index: carbon_core::graphql::primitives::U32(
                (*metadata.instruction_index) as u32,
            ),
            stack_height: carbon_core::graphql::primitives::U32((*metadata.stack_height) as u32),
            slot: metadata
                .slot
                .map(|v| carbon_core::graphql::primitives::U64(*v)),
        }
    }
}
