//! This code was AUTOGENERATED using the Codama library.
use crate::types::KeyIndexInput;
use carbon_core::instruction::InstructionMetadata;
use carbon_core::postgres::metadata::InstructionRowMetadata;

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct StartMiningAsteroidRow {
    #[sqlx(flatten)]
    pub instruction_metadata: InstructionRowMetadata,
    pub input: sqlx::types::Json<KeyIndexInput>,
}

impl StartMiningAsteroidRow {
    pub fn from_parts(
        source: crate::instructions::start_mining_asteroid::StartMiningAsteroid,
        metadata: InstructionMetadata,
    ) -> Self {
        Self {
            instruction_metadata: metadata.into(),
            input: sqlx::types::Json(source.input.into()),
        }
    }
}

impl TryFrom<StartMiningAsteroidRow>
    for crate::instructions::start_mining_asteroid::StartMiningAsteroid
{
    type Error = carbon_core::error::Error;
    fn try_from(source: StartMiningAsteroidRow) -> Result<Self, Self::Error> {
        Ok(Self {
            input: source.input.0,
        })
    }
}

impl carbon_core::postgres::operations::Table
    for crate::instructions::start_mining_asteroid::StartMiningAsteroid
{
    fn table() -> &'static str {
        "start_mining_asteroid_instruction"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__signature",
            "__instruction_index",
            "__stack_height",
            "__slot",
            "input",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for StartMiningAsteroidRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"
            INSERT INTO start_mining_asteroid_instruction (
                "input",
                __signature, __instruction_index, __stack_height, __slot
            ) VALUES (
                $1, $2, $3, $4, $5
            )"#,
        )
        .bind(self.input.clone())
        .bind(self.instruction_metadata.signature.clone())
        .bind(self.instruction_metadata.instruction_index.clone())
        .bind(self.instruction_metadata.stack_height.clone())
        .bind(self.instruction_metadata.slot.clone())
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for StartMiningAsteroidRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"INSERT INTO start_mining_asteroid_instruction (
                "input",
                __signature, __instruction_index, __stack_height, __slot
            ) VALUES (
                $1, $2, $3, $4, $5
            ) ON CONFLICT (
                __signature, __instruction_index, __stack_height
            ) DO UPDATE SET
                "input" = EXCLUDED."input",
                __instruction_index = EXCLUDED.__instruction_index,
                __stack_height = EXCLUDED.__stack_height,
                __slot = EXCLUDED.__slot
            "#,
        )
        .bind(self.input.clone())
        .bind(self.instruction_metadata.signature.clone())
        .bind(self.instruction_metadata.instruction_index.clone())
        .bind(self.instruction_metadata.stack_height.clone())
        .bind(self.instruction_metadata.slot.clone())
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for StartMiningAsteroidRow {
    type Key = (
        String,
        carbon_core::postgres::primitives::U32,
        carbon_core::postgres::primitives::U32,
    );

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"DELETE FROM start_mining_asteroid_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#,
        )
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for StartMiningAsteroidRow {
    type Key = (
        String,
        carbon_core::postgres::primitives::U32,
        carbon_core::postgres::primitives::U32,
    );

    async fn lookup(
        key: Self::Key,
        pool: &sqlx::PgPool,
    ) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(
            r#"SELECT * FROM start_mining_asteroid_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#,
        )
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .fetch_optional(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct StartMiningAsteroidMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for StartMiningAsteroidMigrationOperation {
    async fn up(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(
            r#"CREATE TABLE IF NOT EXISTS start_mining_asteroid_instruction (
                -- Instruction data
                "input" JSONB NOT NULL,
                -- Instruction metadata
                __signature TEXT NOT NULL,
                __instruction_index BIGINT NOT NULL,
                __stack_height BIGINT NOT NULL,
                __slot NUMERIC(20),
                PRIMARY KEY (__signature, __instruction_index, __stack_height)
            )"#,
        )
        .execute(connection)
        .await?;
        Ok(())
    }

    async fn down(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS start_mining_asteroid_instruction"#)
            .execute(connection)
            .await?;
        Ok(())
    }
}
