//! This code was AUTOGENERATED using the Codama library.
pub mod choose_faction_row;

pub use self::choose_faction_row::*;

use super::ProfileFactionInstruction;

pub struct ProfileFactionInstructionsMigration;

impl sqlx_migrator::Migration<sqlx::Postgres> for ProfileFactionInstructionsMigration {
    fn app(&self) -> &str {
        "profile-faction"
    }

    fn name(&self) -> &str {
        "profile_faction_instructions"
    }

    fn operations(&self) -> Vec<Box<dyn sqlx_migrator::Operation<sqlx::Postgres>>> {
        vec![Box::new(ChooseFactionMigrationOperation)]
    }

    fn parents(&self) -> Vec<Box<dyn sqlx_migrator::Migration<sqlx::Postgres>>> {
        vec![]
    }
}

pub struct ProfileFactionInstructionWithMetadata(
    pub ProfileFactionInstruction,
    pub carbon_core::instruction::InstructionMetadata,
);

impl
    From<(
        ProfileFactionInstruction,
        carbon_core::instruction::InstructionMetadata,
    )> for ProfileFactionInstructionWithMetadata
{
    fn from(
        value: (
            ProfileFactionInstruction,
            carbon_core::instruction::InstructionMetadata,
        ),
    ) -> Self {
        ProfileFactionInstructionWithMetadata(value.0, value.1)
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for ProfileFactionInstructionWithMetadata {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        let ProfileFactionInstructionWithMetadata(instruction, metadata) = self;
        match instruction {
            ProfileFactionInstruction::ChooseFaction(instruction) => {
                let row = choose_faction_row::ChooseFactionRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
        }
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for ProfileFactionInstructionWithMetadata {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        let ProfileFactionInstructionWithMetadata(instruction, metadata) = self;
        match instruction {
            ProfileFactionInstruction::ChooseFaction(instruction) => {
                let row = choose_faction_row::ChooseFactionRow::from_parts(
                    instruction.clone(),
                    metadata.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
        }
    }
}
