//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::borsh;
use carbon_core::deserialize::CarbonDeserialize;
use solana_pubkey::Pubkey;

/// `Star` account

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct Star {
    /// The data version of this account.
    pub version: u8,
    /// The name of this `Star`
    #[cfg_attr(feature = "serde", serde(with = "serde_big_array::BigArray"))]
    pub name: [u8; 64],
    /// the game_id that this belongs to
    pub game_id: Pubkey,
    /// the sector that this belongs to
    pub sector: [i64; 2],
    /// size
    pub size: u64,
    /// sub_coordinates as [x, y]
    pub sub_coordinates: [i64; 2],
    /// the star type
    pub star_type: u8,
}

impl Star {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[214, 131, 207, 208, 202, 148, 162, 48] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}
