//! This code was AUTOGENERATED using the Codama library.
use carbon_core::account::AccountMetadata;
use carbon_core::postgres::metadata::AccountRowMetadata;
use carbon_core::postgres::primitives::Pubkey;
use carbon_core::postgres::primitives::U8;
use carbon_core::postgres::primitives::U64;

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct PointsStoreRow {
    #[sqlx(flatten)]
    pub account_metadata: AccountRowMetadata,
    pub version: U8,
    pub point_category: Pubkey,
    pub profile: Pubkey,
    pub bank: Pubkey,
    pub price: U64,
    pub signer_bump: U8,
}

impl PointsStoreRow {
    pub fn from_parts(
        source: crate::accounts::points_store::PointsStore,
        metadata: AccountMetadata,
    ) -> Self {
        Self {
            account_metadata: metadata.into(),
            version: source.version.into(),
            point_category: source.point_category.into(),
            profile: source.profile.into(),
            bank: source.bank.into(),
            price: source.price.into(),
            signer_bump: source.signer_bump.into(),
        }
    }
}

impl TryFrom<PointsStoreRow> for crate::accounts::points_store::PointsStore {
    type Error = carbon_core::error::Error;
    fn try_from(source: PointsStoreRow) -> Result<Self, Self::Error> {
        Ok(Self {
            version: source.version.try_into().map_err(|_| {
                carbon_core::error::Error::Custom(
                    "Failed to convert value from postgres primitive".to_string(),
                )
            })?,
            point_category: *source.point_category,
            profile: *source.profile,
            bank: *source.bank,
            price: *source.price,
            signer_bump: source.signer_bump.try_into().map_err(|_| {
                carbon_core::error::Error::Custom(
                    "Failed to convert value from postgres primitive".to_string(),
                )
            })?,
        })
    }
}

impl carbon_core::postgres::operations::Table for crate::accounts::points_store::PointsStore {
    fn table() -> &'static str {
        "points_store_account"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__pubkey",
            "__slot",
            "version",
            "point_category",
            "profile",
            "bank",
            "price",
            "signer_bump",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for PointsStoreRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"
            INSERT INTO points_store_account (
                "version",
                "point_category",
                "profile",
                "bank",
                "price",
                "signer_bump",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8
            )"#,
        )
        .bind(self.version.clone())
        .bind(self.point_category.clone())
        .bind(self.profile.clone())
        .bind(self.bank.clone())
        .bind(self.price.clone())
        .bind(self.signer_bump.clone())
        .bind(self.account_metadata.pubkey.clone())
        .bind(self.account_metadata.slot.clone())
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for PointsStoreRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"INSERT INTO points_store_account (
                "version",
                "point_category",
                "profile",
                "bank",
                "price",
                "signer_bump",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8
            ) ON CONFLICT (
                __pubkey
            ) DO UPDATE SET
                "version" = EXCLUDED."version",
                "point_category" = EXCLUDED."point_category",
                "profile" = EXCLUDED."profile",
                "bank" = EXCLUDED."bank",
                "price" = EXCLUDED."price",
                "signer_bump" = EXCLUDED."signer_bump",
                __slot = EXCLUDED.__slot
            "#,
        )
        .bind(self.version.clone())
        .bind(self.point_category.clone())
        .bind(self.profile.clone())
        .bind(self.bank.clone())
        .bind(self.price.clone())
        .bind(self.signer_bump.clone())
        .bind(self.account_metadata.pubkey)
        .bind(self.account_metadata.slot.clone())
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for PointsStoreRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"DELETE FROM points_store_account WHERE
                __pubkey = $1
            "#,
        )
        .bind(key)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for PointsStoreRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn lookup(
        key: Self::Key,
        pool: &sqlx::PgPool,
    ) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(
            r#"SELECT * FROM points_store_account WHERE
                __pubkey = $1
            "#,
        )
        .bind(key)
        .fetch_optional(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct PointsStoreMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for PointsStoreMigrationOperation {
    async fn up(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(
            r#"CREATE TABLE IF NOT EXISTS points_store_account (
                -- Account data
                "version" INT2 NOT NULL,
                "point_category" BYTEA NOT NULL,
                "profile" BYTEA NOT NULL,
                "bank" BYTEA NOT NULL,
                "price" NUMERIC(20) NOT NULL,
                "signer_bump" INT2 NOT NULL,
                -- Account metadata
                __pubkey BYTEA NOT NULL,
                __slot NUMERIC(20),
                PRIMARY KEY (__pubkey)
            )"#,
        )
        .execute(connection)
        .await?;
        Ok(())
    }

    async fn down(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS points_store_account"#)
            .execute(connection)
            .await?;
        Ok(())
    }
}
