//! This code was AUTOGENERATED using the Codama library.
use crate::types::graphql::StarbaseLevelInfoGraphQL;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "FactionsStarbaseLevelInfo")]
pub struct FactionsStarbaseLevelInfoGraphQL {
    pub mud: Vec<StarbaseLevelInfoGraphQL>,
    pub oni: Vec<StarbaseLevelInfoGraphQL>,
    pub ustur: Vec<StarbaseLevelInfoGraphQL>,
}

impl From<crate::types::FactionsStarbaseLevelInfo> for FactionsStarbaseLevelInfoGraphQL {
    fn from(original: crate::types::FactionsStarbaseLevelInfo) -> Self {
        Self {
            mud: original.mud.into_iter().map(|item| item.into()).collect(),
            oni: original.oni.into_iter().map(|item| item.into()).collect(),
            ustur: original.ustur.into_iter().map(|item| item.into()).collect(),
        }
    }
}
