//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "Mints")]
pub struct MintsGraphQL {
    pub atlas: Pubkey,
    pub polis: Pubkey,
    pub ammo: Pubkey,
    pub food: Pubkey,
    pub fuel: Pubkey,
    pub repair_kit: Pubkey,
}

impl From<crate::types::Mints> for MintsGraphQL {
    fn from(original: crate::types::Mints) -> Self {
        Self {
            atlas: carbon_core::graphql::primitives::Pubkey(original.atlas),
            polis: carbon_core::graphql::primitives::Pubkey(original.polis),
            ammo: carbon_core::graphql::primitives::Pubkey(original.ammo),
            food: carbon_core::graphql::primitives::Pubkey(original.food),
            fuel: carbon_core::graphql::primitives::Pubkey(original.fuel),
            repair_kit: carbon_core::graphql::primitives::Pubkey(original.repair_kit),
        }
    }
}
