//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::I64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "MoveWarp")]
pub struct MoveWarpGraphQL {
    pub from_sector: Vec<I64>,
    pub to_sector: Vec<I64>,
    pub warp_start: I64,
    pub warp_finish: I64,
}

impl From<crate::types::MoveWarp> for MoveWarpGraphQL {
    fn from(original: crate::types::MoveWarp) -> Self {
        Self {
            from_sector: original
                .from_sector
                .into_iter()
                .map(|item| carbon_core::graphql::primitives::I64(item))
                .collect(),
            to_sector: original
                .to_sector
                .into_iter()
                .map(|item| carbon_core::graphql::primitives::I64(item))
                .collect(),
            warp_start: carbon_core::graphql::primitives::I64(original.warp_start),
            warp_finish: carbon_core::graphql::primitives::I64(original.warp_finish),
        }
    }
}
