//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U32;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "ProgressionItemUnpacked")]
pub struct ProgressionItemUnpackedGraphQL {
    pub value: U32,
}

impl From<crate::types::ProgressionItemUnpacked> for ProgressionItemUnpackedGraphQL {
    fn from(original: crate::types::ProgressionItemUnpacked) -> Self {
        Self {
            value: carbon_core::graphql::primitives::U32(original.value),
        }
    }
}
