//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::I64;
use carbon_core::graphql::primitives::U8;
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "RegisterPlanetInput")]
pub struct RegisterPlanetInputGraphQL {
    pub name: Vec<U8>,
    pub size: U64,
    pub max_hp: U64,
    pub sub_coordinates: Vec<I64>,
    pub planet_type: U8,
    pub position: U8,
    pub key_index: i32,
}

impl From<crate::types::RegisterPlanetInput> for RegisterPlanetInputGraphQL {
    fn from(original: crate::types::RegisterPlanetInput) -> Self {
        Self {
            name: original
                .name
                .into_iter()
                .map(|item| carbon_core::graphql::primitives::U8(item))
                .collect(),
            size: carbon_core::graphql::primitives::U64(original.size),
            max_hp: carbon_core::graphql::primitives::U64(original.max_hp),
            sub_coordinates: original
                .sub_coordinates
                .into_iter()
                .map(|item| carbon_core::graphql::primitives::I64(item))
                .collect(),
            planet_type: carbon_core::graphql::primitives::U8(original.planet_type),
            position: carbon_core::graphql::primitives::U8(original.position),
            key_index: original.key_index as i32,
        }
    }
}
