//! This code was AUTOGENERATED using the Codama library.
use crate::types::graphql::RiskZoneDataGraphQL;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "RiskZonesDataUnpacked")]
pub struct RiskZonesDataUnpackedGraphQL {
    pub mud_security_zone: RiskZoneDataGraphQL,
    pub oni_security_zone: RiskZoneDataGraphQL,
    pub ustur_security_zone: RiskZoneDataGraphQL,
    pub high_risk_zone: RiskZoneDataGraphQL,
    pub medium_risk_zone: RiskZoneDataGraphQL,
}

impl From<crate::types::RiskZonesDataUnpacked> for RiskZonesDataUnpackedGraphQL {
    fn from(original: crate::types::RiskZonesDataUnpacked) -> Self {
        Self {
            mud_security_zone: original.mud_security_zone.into(),
            oni_security_zone: original.oni_security_zone.into(),
            ustur_security_zone: original.ustur_security_zone.into(),
            high_risk_zone: original.high_risk_zone.into(),
            medium_risk_zone: original.medium_risk_zone.into(),
        }
    }
}
