//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "StarbaseWithdrawCraftingIngredientInput")]
pub struct StarbaseWithdrawCraftingIngredientInputGraphQL {
    pub amount: U64,
    pub ingredient_index: i32,
    pub key_index: i32,
}

impl From<crate::types::StarbaseWithdrawCraftingIngredientInput>
    for StarbaseWithdrawCraftingIngredientInputGraphQL
{
    fn from(original: crate::types::StarbaseWithdrawCraftingIngredientInput) -> Self {
        Self {
            amount: carbon_core::graphql::primitives::U64(original.amount),
            ingredient_index: original.ingredient_index as i32,
            key_index: original.key_index as i32,
        }
    }
}
