//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U8;
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "StarbaseLevelInfo")]
pub struct StarbaseLevelInfoGraphQL {
    pub recipe_for_upgrade: Pubkey,
    pub recipe_category_for_level: Pubkey,
    pub hp: U64,
    pub sp: U64,
    pub sector_ring_available: U8,
    pub warp_lane_movement_fee: U64,
}

impl From<crate::types::StarbaseLevelInfo> for StarbaseLevelInfoGraphQL {
    fn from(original: crate::types::StarbaseLevelInfo) -> Self {
        Self {
            recipe_for_upgrade: carbon_core::graphql::primitives::Pubkey(
                original.recipe_for_upgrade,
            ),
            recipe_category_for_level: carbon_core::graphql::primitives::Pubkey(
                original.recipe_category_for_level,
            ),
            hp: carbon_core::graphql::primitives::U64(original.hp),
            sp: carbon_core::graphql::primitives::U64(original.sp),
            sector_ring_available: carbon_core::graphql::primitives::U8(
                original.sector_ring_available,
            ),
            warp_lane_movement_fee: carbon_core::graphql::primitives::U64(
                original.warp_lane_movement_fee,
            ),
        }
    }
}
