//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
/// A faction that a player can belong to.

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub enum Faction {
    Unaligned,
    MUD,
    ONI,
    Ustur,
}
