//! This code was AUTOGENERATED using the Codama library.
use carbon_core::account::AccountMetadata;
use carbon_core::postgres::metadata::AccountRowMetadata;
use carbon_core::postgres::primitives::Pubkey;
use carbon_core::postgres::primitives::U8;
use carbon_core::postgres::primitives::U64;

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct FeePayerRatesRow {
    #[sqlx(flatten)]
    pub account_metadata: AccountRowMetadata,
    pub version: U8,
    pub owning_profile: Pubkey,
    pub token_mint: Pubkey,
    pub token_owner: Pubkey,
    pub token_limit: U64,
    pub conversion_rate: U64,
}

impl FeePayerRatesRow {
    pub fn from_parts(
        source: crate::accounts::fee_payer_rates::FeePayerRates,
        metadata: AccountMetadata,
    ) -> Self {
        Self {
            account_metadata: metadata.into(),
            version: source.version.into(),
            owning_profile: source.owning_profile.into(),
            token_mint: source.token_mint.into(),
            token_owner: source.token_owner.into(),
            token_limit: source.token_limit.into(),
            conversion_rate: source.conversion_rate.into(),
        }
    }
}

impl TryFrom<FeePayerRatesRow> for crate::accounts::fee_payer_rates::FeePayerRates {
    type Error = carbon_core::error::Error;
    fn try_from(source: FeePayerRatesRow) -> Result<Self, Self::Error> {
        Ok(Self {
            version: source.version.try_into().map_err(|_| {
                carbon_core::error::Error::Custom(
                    "Failed to convert value from postgres primitive".to_string(),
                )
            })?,
            owning_profile: *source.owning_profile,
            token_mint: *source.token_mint,
            token_owner: *source.token_owner,
            token_limit: *source.token_limit,
            conversion_rate: *source.conversion_rate,
        })
    }
}

impl carbon_core::postgres::operations::Table for crate::accounts::fee_payer_rates::FeePayerRates {
    fn table() -> &'static str {
        "fee_payer_rates_account"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__pubkey",
            "__slot",
            "version",
            "owning_profile",
            "token_mint",
            "token_owner",
            "token_limit",
            "conversion_rate",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for FeePayerRatesRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"
            INSERT INTO fee_payer_rates_account (
                "version",
                "owning_profile",
                "token_mint",
                "token_owner",
                "token_limit",
                "conversion_rate",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8
            )"#,
        )
        .bind(self.version.clone())
        .bind(self.owning_profile.clone())
        .bind(self.token_mint.clone())
        .bind(self.token_owner.clone())
        .bind(self.token_limit.clone())
        .bind(self.conversion_rate.clone())
        .bind(self.account_metadata.pubkey.clone())
        .bind(self.account_metadata.slot.clone())
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for FeePayerRatesRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"INSERT INTO fee_payer_rates_account (
                "version",
                "owning_profile",
                "token_mint",
                "token_owner",
                "token_limit",
                "conversion_rate",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8
            ) ON CONFLICT (
                __pubkey
            ) DO UPDATE SET
                "version" = EXCLUDED."version",
                "owning_profile" = EXCLUDED."owning_profile",
                "token_mint" = EXCLUDED."token_mint",
                "token_owner" = EXCLUDED."token_owner",
                "token_limit" = EXCLUDED."token_limit",
                "conversion_rate" = EXCLUDED."conversion_rate",
                __slot = EXCLUDED.__slot
            "#,
        )
        .bind(self.version.clone())
        .bind(self.owning_profile.clone())
        .bind(self.token_mint.clone())
        .bind(self.token_owner.clone())
        .bind(self.token_limit.clone())
        .bind(self.conversion_rate.clone())
        .bind(self.account_metadata.pubkey)
        .bind(self.account_metadata.slot.clone())
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for FeePayerRatesRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"DELETE FROM fee_payer_rates_account WHERE
                __pubkey = $1
            "#,
        )
        .bind(key)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for FeePayerRatesRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn lookup(
        key: Self::Key,
        pool: &sqlx::PgPool,
    ) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(
            r#"SELECT * FROM fee_payer_rates_account WHERE
                __pubkey = $1
            "#,
        )
        .bind(key)
        .fetch_optional(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct FeePayerRatesMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for FeePayerRatesMigrationOperation {
    async fn up(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(
            r#"CREATE TABLE IF NOT EXISTS fee_payer_rates_account (
                -- Account data
                "version" INT2 NOT NULL,
                "owning_profile" BYTEA NOT NULL,
                "token_mint" BYTEA NOT NULL,
                "token_owner" BYTEA NOT NULL,
                "token_limit" NUMERIC(20) NOT NULL,
                "conversion_rate" NUMERIC(20) NOT NULL,
                -- Account metadata
                __pubkey BYTEA NOT NULL,
                __slot NUMERIC(20),
                PRIMARY KEY (__pubkey)
            )"#,
        )
        .execute(connection)
        .await?;
        Ok(())
    }

    async fn down(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS fee_payer_rates_account"#)
            .execute(connection)
            .await?;
        Ok(())
    }
}
