//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U8;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "DisbandedFleet")]
pub struct DisbandedFleetGraphQL {
    pub account_metadata: crate::accounts::graphql::AccountMetadataGraphQL,
    pub version: U8,
    pub game_id: Pubkey,
    pub owner_profile: Pubkey,
    pub starbase: Pubkey,
    pub fleet_label: Vec<U8>,
    pub fleet_ships: Pubkey,
    pub bump: U8,
}

impl TryFrom<crate::accounts::postgres::DisbandedFleetRow> for DisbandedFleetGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::accounts::postgres::DisbandedFleetRow) -> Result<Self, Self::Error> {
        Ok(Self {
            account_metadata: row.account_metadata.into(),
            version: carbon_core::graphql::primitives::U8((*row.version) as u8),
            game_id: carbon_core::graphql::primitives::Pubkey(row.game_id.0),
            owner_profile: carbon_core::graphql::primitives::Pubkey(row.owner_profile.0),
            starbase: carbon_core::graphql::primitives::Pubkey(row.starbase.0),
            fleet_label: row
                .fleet_label
                .into_iter()
                .map(|item| carbon_core::graphql::primitives::U8(item))
                .collect(),
            fleet_ships: carbon_core::graphql::primitives::Pubkey(row.fleet_ships.0),
            bump: carbon_core::graphql::primitives::U8((*row.bump) as u8),
        })
    }
}
