//! This code was AUTOGENERATED using the Codama library.
//!
//! Phase-E crew-individuation addition. Source: `program/src/instructions/admin.rs`
//! (`SetCrewConfig`). Arg field order = admin.rs:43-49: `key_index`, `crew_config`
//! (`Option<Pubkey>` — `Some` switches the crew layer ON, `None` OFF). Account set =
//! admin.rs:56-69: `profile_validation` (admin `MANAGE_CREW_CONFIG`), `game` (Mut — the
//! packed-header `crew_config` is written). NO flag gate (this IS the flag setter).
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq, Eq, Hash)]
pub struct SetCrewConfig {
    /// The index of the key in the player profile.
    pub key_index: u16,
    /// The new `crew_config` value: `Some` => ON (the crew-config account key), `None` => OFF.
    pub crew_config: Option<solana_pubkey::Pubkey>,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SetCrewConfigInstructionAccounts {
    // ProfileValidation<true> -> fixed 4-acct prefix (signer, profile, certificate [SAGE_ID-sentinel when none], program); cf. create_recipe.
    pub profile_validation_signer: solana_pubkey::Pubkey,
    pub profile_validation_profile: solana_pubkey::Pubkey,
    pub profile_validation_certificate: solana_pubkey::Pubkey,
    pub profile_validation_program: solana_pubkey::Pubkey,
    pub game: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl SetCrewConfig {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[22, 105, 28, 85, 145, 112, 121, 194] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for SetCrewConfig {
    type ArrangedAccounts = SetCrewConfigInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let profile_validation_signer = next_account(&mut iter)?;
        let profile_validation_profile = next_account(&mut iter)?;
        let profile_validation_certificate = next_account(&mut iter)?;
        let profile_validation_program = next_account(&mut iter)?;
        let game = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(SetCrewConfigInstructionAccounts {
            profile_validation_signer,
            profile_validation_profile,
            profile_validation_certificate,
            profile_validation_program,
            game,
            remaining: remaining.to_vec(),
        })
    }
}
