//! This code was AUTOGENERATED using the Codama library.
use crate::types::UpdateShipInput;
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct UpdateShip {
    pub input: UpdateShipInput,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct UpdateShipInstructionAccounts {
    pub key: solana_pubkey::Pubkey,
    pub profile: solana_pubkey::Pubkey,
    pub game_id: solana_pubkey::Pubkey,
    pub ship: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl UpdateShip {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[103, 231, 36, 213, 187, 72, 42, 252] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for UpdateShip {
    type ArrangedAccounts = UpdateShipInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let key = next_account(&mut iter)?;
        let profile = next_account(&mut iter)?;
        let game_id = next_account(&mut iter)?;
        let ship = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(UpdateShipInstructionAccounts {
            key,
            profile,
            game_id,
            ship,
            remaining: remaining.to_vec(),
        })
    }
}
