//! This code was AUTOGENERATED using the Codama library.
use crate::PROGRAM_ID;
use crate::ProfileVaultDecoder;

#[cfg(feature = "postgres")]
pub mod postgres;

#[cfg(feature = "graphql")]
pub mod graphql;

pub mod vault_authority;

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(tag = "type", content = "data"))]
pub enum ProfileVaultAccount {
    VaultAuthority(Box<vault_authority::VaultAuthority>),
}

impl<'a> carbon_core::account::AccountDecoder<'a> for ProfileVaultDecoder {
    type AccountType = ProfileVaultAccount;

    fn decode_account(
        &self,
        account: &'a solana_account::Account,
    ) -> Option<carbon_core::account::DecodedAccount<Self::AccountType>> {
        if account.owner != PROGRAM_ID {
            return None;
        }

        let data = account.data.as_slice();

        {
            if let Some(decoded) = vault_authority::VaultAuthority::decode(data) {
                return Some(carbon_core::account::DecodedAccount {
                    lamports: account.lamports,
                    data: ProfileVaultAccount::VaultAuthority(Box::new(decoded)),
                    owner: account.owner,
                    executable: account.executable,
                    rent_epoch: account.rent_epoch,
                });
            }
        }

        None
    }
}
