//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::borsh;
use carbon_core::deserialize::CarbonDeserialize;
use solana_pubkey::Pubkey;

/// An authority over vaults for a profile

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct VaultAuthority {
    /// The data version of this account.
    pub version: u8,
    /// The profile the authority is for
    pub profile: Pubkey,
    /// The seed of this authority
    pub vault_seed: Pubkey,
    /// The bump for this authority
    pub vault_bump: u8,
}

impl VaultAuthority {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[132, 34, 187, 202, 202, 195, 211, 53] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}
