//! This code was AUTOGENERATED using the Codama library.
use carbon_core::instruction::InstructionMetadata;
use carbon_core::postgres::metadata::InstructionRowMetadata;
use carbon_core::postgres::primitives::U64;

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct TakeBidWnsRow {
    #[sqlx(flatten)]
    pub instruction_metadata: InstructionRowMetadata,
    pub min_amount: U64,
}

impl TakeBidWnsRow {
    pub fn from_parts(
        source: crate::instructions::take_bid_wns::TakeBidWns,
        metadata: InstructionMetadata,
    ) -> Self {
        Self {
            instruction_metadata: metadata.into(),
            min_amount: source.min_amount.into(),
        }
    }
}

impl TryFrom<TakeBidWnsRow> for crate::instructions::take_bid_wns::TakeBidWns {
    type Error = carbon_core::error::Error;
    fn try_from(source: TakeBidWnsRow) -> Result<Self, Self::Error> {
        Ok(Self {
            min_amount: *source.min_amount,
        })
    }
}

impl carbon_core::postgres::operations::Table for crate::instructions::take_bid_wns::TakeBidWns {
    fn table() -> &'static str {
        "take_bid_wns_instruction"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__signature",
            "__instruction_index",
            "__stack_height",
            "__slot",
            "min_amount",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for TakeBidWnsRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"
            INSERT INTO take_bid_wns_instruction (
                "min_amount",
                __signature, __instruction_index, __stack_height, __slot
            ) VALUES (
                $1, $2, $3, $4, $5
            )"#,
        )
        .bind(self.min_amount.clone())
        .bind(self.instruction_metadata.signature.clone())
        .bind(self.instruction_metadata.instruction_index.clone())
        .bind(self.instruction_metadata.stack_height.clone())
        .bind(self.instruction_metadata.slot.clone())
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for TakeBidWnsRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"INSERT INTO take_bid_wns_instruction (
                "min_amount",
                __signature, __instruction_index, __stack_height, __slot
            ) VALUES (
                $1, $2, $3, $4, $5
            ) ON CONFLICT (
                __signature, __instruction_index, __stack_height
            ) DO UPDATE SET
                "min_amount" = EXCLUDED."min_amount",
                __instruction_index = EXCLUDED.__instruction_index,
                __stack_height = EXCLUDED.__stack_height,
                __slot = EXCLUDED.__slot
            "#,
        )
        .bind(self.min_amount.clone())
        .bind(self.instruction_metadata.signature.clone())
        .bind(self.instruction_metadata.instruction_index.clone())
        .bind(self.instruction_metadata.stack_height.clone())
        .bind(self.instruction_metadata.slot.clone())
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for TakeBidWnsRow {
    type Key = (
        String,
        carbon_core::postgres::primitives::U32,
        carbon_core::postgres::primitives::U32,
    );

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"DELETE FROM take_bid_wns_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#,
        )
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for TakeBidWnsRow {
    type Key = (
        String,
        carbon_core::postgres::primitives::U32,
        carbon_core::postgres::primitives::U32,
    );

    async fn lookup(
        key: Self::Key,
        pool: &sqlx::PgPool,
    ) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(
            r#"SELECT * FROM take_bid_wns_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#,
        )
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .fetch_optional(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct TakeBidWnsMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for TakeBidWnsMigrationOperation {
    async fn up(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(
            r#"CREATE TABLE IF NOT EXISTS take_bid_wns_instruction (
                -- Instruction data
                "min_amount" NUMERIC(20) NOT NULL,
                -- Instruction metadata
                __signature TEXT NOT NULL,
                __instruction_index BIGINT NOT NULL,
                __stack_height BIGINT NOT NULL,
                __slot NUMERIC(20),
                PRIMARY KEY (__signature, __instruction_index, __stack_height)
            )"#,
        )
        .execute(connection)
        .await?;
        Ok(())
    }

    async fn down(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS take_bid_wns_instruction"#)
            .execute(connection)
            .await?;
        Ok(())
    }
}
