//! This code was AUTOGENERATED using the Codama library.
use crate::CargoDecoder;
use crate::PROGRAM_ID;

#[cfg(feature = "postgres")]
pub mod postgres;

#[cfg(feature = "graphql")]
pub mod graphql;

pub mod cargo_pod;
pub mod cargo_stats_definition;
pub mod cargo_type;

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(tag = "type", content = "data"))]
pub enum CargoAccount {
    CargoPod(Box<cargo_pod::CargoPod>),
    CargoStatsDefinition(Box<cargo_stats_definition::CargoStatsDefinition>),
    CargoType(Box<cargo_type::CargoType>),
}

impl<'a> carbon_core::account::AccountDecoder<'a> for CargoDecoder {
    type AccountType = CargoAccount;

    fn decode_account(
        &self,
        account: &'a solana_account::Account,
    ) -> Option<carbon_core::account::DecodedAccount<Self::AccountType>> {
        if account.owner != PROGRAM_ID {
            return None;
        }

        let data = account.data.as_slice();

        {
            if let Some(decoded) = cargo_pod::CargoPod::decode(data) {
                return Some(carbon_core::account::DecodedAccount {
                    lamports: account.lamports,
                    data: CargoAccount::CargoPod(Box::new(decoded)),
                    owner: account.owner,
                    executable: account.executable,
                    rent_epoch: account.rent_epoch,
                });
            }
        }
        {
            if let Some(decoded) = cargo_stats_definition::CargoStatsDefinition::decode(data) {
                return Some(carbon_core::account::DecodedAccount {
                    lamports: account.lamports,
                    data: CargoAccount::CargoStatsDefinition(Box::new(decoded)),
                    owner: account.owner,
                    executable: account.executable,
                    rent_epoch: account.rent_epoch,
                });
            }
        }
        {
            if let Some(decoded) = cargo_type::CargoType::decode(data) {
                return Some(carbon_core::account::DecodedAccount {
                    lamports: account.lamports,
                    data: CargoAccount::CargoType(Box::new(decoded)),
                    owner: account.owner,
                    executable: account.executable,
                    rent_epoch: account.rent_epoch,
                });
            }
        }

        None
    }
}
