//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::borsh;
use carbon_core::deserialize::CarbonDeserialize;
use solana_pubkey::Pubkey;

/// `SftRedemption` is a data account used for handling the redemption of SFTs in the Crew program.
/// This account details the number and type of cNFTs that are to be minted in exchange for the given SFT.

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct SftRedemption {
    /// The data version
    pub version: u8,
    /// the bump seed
    pub bump: u8,
    /// The pack type that is being redeemed.
    pub pack_type: Pubkey,
    /// The mint of the SFT that is being exchanged.
    pub sft_mint: Pubkey,
    /// The registered Crew Config for the deployed Crew program
    pub crew_config: Pubkey,
    /// The number of cNFTs being received in exchange for the SFT
    pub redemption_amount: u32,
}

impl SftRedemption {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[58, 90, 84, 49, 168, 14, 195, 190] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}
