//! This code was AUTOGENERATED using the Codama library.
use carbon_core::instruction::InstructionMetadata;
use carbon_core::postgres::metadata::InstructionRowMetadata;
use carbon_core::postgres::primitives::U16;
use carbon_core::postgres::primitives::U64;

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct CreateContractRow {
    #[sqlx(flatten)]
    pub instruction_metadata: InstructionRowMetadata,
    pub rate: U64,
    pub duration_min: U64,
    pub duration_max: U64,
    pub payments_feq: String,
    pub owner_key_index: U16,
}

impl CreateContractRow {
    pub fn from_parts(
        source: crate::instructions::create_contract::CreateContract,
        metadata: InstructionMetadata,
    ) -> Self {
        Self {
            instruction_metadata: metadata.into(),
            rate: source.rate.into(),
            duration_min: source.duration_min.into(),
            duration_max: source.duration_max.into(),
            payments_feq: source.payments_feq.into(),
            owner_key_index: source.owner_key_index.into(),
        }
    }
}

impl TryFrom<CreateContractRow> for crate::instructions::create_contract::CreateContract {
    type Error = carbon_core::error::Error;
    fn try_from(source: CreateContractRow) -> Result<Self, Self::Error> {
        Ok(Self {
            rate: *source.rate,
            duration_min: *source.duration_min,
            duration_max: *source.duration_max,
            payments_feq: source.payments_feq.into(),
            owner_key_index: source.owner_key_index.try_into().map_err(|_| {
                carbon_core::error::Error::Custom(
                    "Failed to convert value from postgres primitive".to_string(),
                )
            })?,
        })
    }
}

impl carbon_core::postgres::operations::Table
    for crate::instructions::create_contract::CreateContract
{
    fn table() -> &'static str {
        "create_contract_instruction"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__signature",
            "__instruction_index",
            "__stack_height",
            "__slot",
            "rate",
            "duration_min",
            "duration_max",
            "payments_feq",
            "owner_key_index",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for CreateContractRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"
            INSERT INTO create_contract_instruction (
                "rate",
                "duration_min",
                "duration_max",
                "payments_feq",
                "owner_key_index",
                __signature, __instruction_index, __stack_height, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8, $9
            )"#,
        )
        .bind(self.rate.clone())
        .bind(self.duration_min.clone())
        .bind(self.duration_max.clone())
        .bind(self.payments_feq.clone())
        .bind(self.owner_key_index.clone())
        .bind(self.instruction_metadata.signature.clone())
        .bind(self.instruction_metadata.instruction_index.clone())
        .bind(self.instruction_metadata.stack_height.clone())
        .bind(self.instruction_metadata.slot.clone())
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for CreateContractRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"INSERT INTO create_contract_instruction (
                "rate",
                "duration_min",
                "duration_max",
                "payments_feq",
                "owner_key_index",
                __signature, __instruction_index, __stack_height, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8, $9
            ) ON CONFLICT (
                __signature, __instruction_index, __stack_height
            ) DO UPDATE SET
                "rate" = EXCLUDED."rate",
                "duration_min" = EXCLUDED."duration_min",
                "duration_max" = EXCLUDED."duration_max",
                "payments_feq" = EXCLUDED."payments_feq",
                "owner_key_index" = EXCLUDED."owner_key_index",
                __instruction_index = EXCLUDED.__instruction_index,
                __stack_height = EXCLUDED.__stack_height,
                __slot = EXCLUDED.__slot
            "#,
        )
        .bind(self.rate.clone())
        .bind(self.duration_min.clone())
        .bind(self.duration_max.clone())
        .bind(self.payments_feq.clone())
        .bind(self.owner_key_index.clone())
        .bind(self.instruction_metadata.signature.clone())
        .bind(self.instruction_metadata.instruction_index.clone())
        .bind(self.instruction_metadata.stack_height.clone())
        .bind(self.instruction_metadata.slot.clone())
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for CreateContractRow {
    type Key = (
        String,
        carbon_core::postgres::primitives::U32,
        carbon_core::postgres::primitives::U32,
    );

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"DELETE FROM create_contract_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#,
        )
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for CreateContractRow {
    type Key = (
        String,
        carbon_core::postgres::primitives::U32,
        carbon_core::postgres::primitives::U32,
    );

    async fn lookup(
        key: Self::Key,
        pool: &sqlx::PgPool,
    ) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(
            r#"SELECT * FROM create_contract_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#,
        )
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .fetch_optional(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct CreateContractMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for CreateContractMigrationOperation {
    async fn up(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(
            r#"CREATE TABLE IF NOT EXISTS create_contract_instruction (
                -- Instruction data
                "rate" NUMERIC(20) NOT NULL,
                "duration_min" NUMERIC(20) NOT NULL,
                "duration_max" NUMERIC(20) NOT NULL,
                "payments_feq" TEXT NOT NULL,
                "owner_key_index" INT4 NOT NULL,
                -- Instruction metadata
                __signature TEXT NOT NULL,
                __instruction_index BIGINT NOT NULL,
                __stack_height BIGINT NOT NULL,
                __slot NUMERIC(20),
                PRIMARY KEY (__signature, __instruction_index, __stack_height)
            )"#,
        )
        .execute(connection)
        .await?;
        Ok(())
    }

    async fn down(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS create_contract_instruction"#)
            .execute(connection)
            .await?;
        Ok(())
    }
}
