//! This code was AUTOGENERATED using the Codama library.
pub mod bid_schema;
pub mod buy_core_schema;
pub mod buy_schema;
pub mod buy_spl_schema;
pub mod close_expired_listing_schema;
pub mod delist_schema;
pub mod edit_schema;
pub mod list_core_schema;
pub mod list_schema;
pub mod take_bid_core_schema;
pub mod take_bid_full_meta_schema;
pub mod take_bid_legacy_schema;
pub mod take_bid_meta_hash_schema;
pub mod take_bid_t22_schema;
pub mod take_bid_wns_schema;
pub mod tcomp_noop_schema;
pub mod withdraw_fees_schema;

pub use bid_schema::*;
pub use buy_core_schema::*;
pub use buy_schema::*;
pub use buy_spl_schema::*;
pub use close_expired_listing_schema::*;
pub use delist_schema::*;
pub use edit_schema::*;
pub use list_core_schema::*;
pub use list_schema::*;
pub use take_bid_core_schema::*;
pub use take_bid_full_meta_schema::*;
pub use take_bid_legacy_schema::*;
pub use take_bid_meta_hash_schema::*;
pub use take_bid_t22_schema::*;
pub use take_bid_wns_schema::*;
pub use tcomp_noop_schema::*;
pub use withdraw_fees_schema::*;

use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "InstructionMetadata")]
pub struct InstructionMetadataGraphQL {
    pub signature: String,
    pub instruction_index: carbon_core::graphql::primitives::U32,
    pub stack_height: carbon_core::graphql::primitives::U32,
    pub slot: Option<carbon_core::graphql::primitives::U64>,
}

impl From<carbon_core::postgres::metadata::InstructionRowMetadata> for InstructionMetadataGraphQL {
    fn from(metadata: carbon_core::postgres::metadata::InstructionRowMetadata) -> Self {
        Self {
            signature: metadata.signature,
            instruction_index: carbon_core::graphql::primitives::U32(
                (*metadata.instruction_index) as u32,
            ),
            stack_height: carbon_core::graphql::primitives::U32((*metadata.stack_height) as u32),
            slot: metadata
                .slot
                .map(|v| carbon_core::graphql::primitives::U64(*v)),
        }
    }
}
