//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U8;
use carbon_core::graphql::primitives::U32;
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "TakeBidMetaHash")]
pub struct TakeBidMetaHashGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub nonce: U64,
    pub index: U32,
    pub root: Vec<U8>,
    pub meta_hash: Vec<U8>,
    pub creator_shares: Vec<U8>,
    pub creator_verified: Vec<bool>,
    pub seller_fee_basis_points: i32,
    pub min_amount: U64,
    pub optional_royalty_pct: Option<i32>,
}

impl TryFrom<crate::instructions::postgres::TakeBidMetaHashRow> for TakeBidMetaHashGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(
        row: crate::instructions::postgres::TakeBidMetaHashRow,
    ) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            nonce: carbon_core::graphql::primitives::U64(*row.nonce),
            index: carbon_core::graphql::primitives::U32((*row.index) as u32),
            root: row
                .root
                .into_iter()
                .map(|item| carbon_core::graphql::primitives::U8(item))
                .collect(),
            meta_hash: row
                .meta_hash
                .into_iter()
                .map(|item| carbon_core::graphql::primitives::U8(item))
                .collect(),
            creator_shares: row
                .creator_shares
                .into_iter()
                .map(|item| carbon_core::graphql::primitives::U8(item))
                .collect(),
            creator_verified: row.creator_verified.into_iter().map(|item| item).collect(),
            seller_fee_basis_points: (*row.seller_fee_basis_points) as i32,
            min_amount: carbon_core::graphql::primitives::U64(*row.min_amount),
            optional_royalty_pct: row.optional_royalty_pct.map(|v| (*v) as i32),
        })
    }
}
