//! This code was AUTOGENERATED using the Codama library.
pub mod accept_role_invitation_schema;
pub mod add_existing_member_to_role_schema;
pub mod add_keys_schema;
pub mod adjust_auth_schema;
pub mod create_profile_schema;
pub mod create_role_schema;
pub mod invite_member_to_role_schema;
pub mod join_role_schema;
pub mod leave_role_schema;
pub mod remove_keys_schema;
pub mod remove_member_from_role_schema;
pub mod remove_role_schema;
pub mod set_name_schema;
pub mod set_role_accepting_members_schema;
pub mod set_role_authorizer_schema;
pub mod set_role_name_schema;
pub mod set_role_not_accepting_members_schema;

pub use accept_role_invitation_schema::*;
pub use add_existing_member_to_role_schema::*;
pub use add_keys_schema::*;
pub use adjust_auth_schema::*;
pub use create_profile_schema::*;
pub use create_role_schema::*;
pub use invite_member_to_role_schema::*;
pub use join_role_schema::*;
pub use leave_role_schema::*;
pub use remove_keys_schema::*;
pub use remove_member_from_role_schema::*;
pub use remove_role_schema::*;
pub use set_name_schema::*;
pub use set_role_accepting_members_schema::*;
pub use set_role_authorizer_schema::*;
pub use set_role_name_schema::*;
pub use set_role_not_accepting_members_schema::*;

use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "InstructionMetadata")]
pub struct InstructionMetadataGraphQL {
    pub signature: String,
    pub instruction_index: carbon_core::graphql::primitives::U32,
    pub stack_height: carbon_core::graphql::primitives::U32,
    pub slot: Option<carbon_core::graphql::primitives::U64>,
}

impl From<carbon_core::postgres::metadata::InstructionRowMetadata> for InstructionMetadataGraphQL {
    fn from(metadata: carbon_core::postgres::metadata::InstructionRowMetadata) -> Self {
        Self {
            signature: metadata.signature,
            instruction_index: carbon_core::graphql::primitives::U32(
                (*metadata.instruction_index) as u32,
            ),
            stack_height: carbon_core::graphql::primitives::U32((*metadata.stack_height) as u32),
            slot: metadata
                .slot
                .map(|v| carbon_core::graphql::primitives::U64(*v)),
        }
    }
}
