//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "ProcessInitializeBuy")]
pub struct ProcessInitializeBuyGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub price: U64,
    pub origination_qty: U64,
}

impl TryFrom<crate::instructions::postgres::ProcessInitializeBuyRow>
    for ProcessInitializeBuyGraphQL
{
    type Error = carbon_core::error::Error;
    fn try_from(
        row: crate::instructions::postgres::ProcessInitializeBuyRow,
    ) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            price: carbon_core::graphql::primitives::U64(*row.price),
            origination_qty: carbon_core::graphql::primitives::U64(*row.origination_qty),
        })
    }
}
