//! This code was AUTOGENERATED using the Codama library.
use crate::PROGRAM_ID;
use crate::PlayerProfileDecoder;
#[cfg(feature = "postgres")]
pub mod postgres;

#[cfg(feature = "graphql")]
pub mod graphql;

pub mod accept_role_invitation;
pub mod add_existing_member_to_role;
pub mod add_keys;
pub mod adjust_auth;
pub mod create_profile;
pub mod create_role;
pub mod invite_member_to_role;
pub mod join_role;
pub mod leave_role;
pub mod remove_keys;
pub mod remove_member_from_role;
pub mod remove_role;
pub mod set_name;
pub mod set_role_accepting_members;
pub mod set_role_authorizer;
pub mod set_role_name;
pub mod set_role_not_accepting_members;

pub use self::accept_role_invitation::*;
pub use self::add_existing_member_to_role::*;
pub use self::add_keys::*;
pub use self::adjust_auth::*;
pub use self::create_profile::*;
pub use self::create_role::*;
pub use self::invite_member_to_role::*;
pub use self::join_role::*;
pub use self::leave_role::*;
pub use self::remove_keys::*;
pub use self::remove_member_from_role::*;
pub use self::remove_role::*;
pub use self::set_name::*;
pub use self::set_role_accepting_members::*;
pub use self::set_role_authorizer::*;
pub use self::set_role_name::*;
pub use self::set_role_not_accepting_members::*;

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(tag = "type", content = "data"))]
pub enum PlayerProfileInstruction {
    AcceptRoleInvitation(AcceptRoleInvitation),
    AddExistingMemberToRole(AddExistingMemberToRole),
    AddKeys(AddKeys),
    AdjustAuth(AdjustAuth),
    CreateProfile(CreateProfile),
    CreateRole(CreateRole),
    InviteMemberToRole(InviteMemberToRole),
    JoinRole(JoinRole),
    LeaveRole(LeaveRole),
    RemoveKeys(RemoveKeys),
    RemoveMemberFromRole(RemoveMemberFromRole),
    RemoveRole(RemoveRole),
    SetName(SetName),
    SetRoleAcceptingMembers(SetRoleAcceptingMembers),
    SetRoleAuthorizer(SetRoleAuthorizer),
    SetRoleName(SetRoleName),
    SetRoleNotAcceptingMembers(SetRoleNotAcceptingMembers),
}

impl carbon_core::instruction::InstructionDecoder<'_> for PlayerProfileDecoder {
    type InstructionType = PlayerProfileInstruction;

    fn decode_instruction(
        &self,
        instruction: &solana_instruction::Instruction,
    ) -> Option<carbon_core::instruction::DecodedInstruction<Self::InstructionType>> {
        if !instruction.program_id.eq(&PROGRAM_ID) {
            return None;
        }

        let data = instruction.data.as_slice();

        {
            if let Some(decoded) = accept_role_invitation::AcceptRoleInvitation::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PlayerProfileInstruction::AcceptRoleInvitation(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) =
                add_existing_member_to_role::AddExistingMemberToRole::decode(data)
            {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PlayerProfileInstruction::AddExistingMemberToRole(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = add_keys::AddKeys::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PlayerProfileInstruction::AddKeys(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = adjust_auth::AdjustAuth::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PlayerProfileInstruction::AdjustAuth(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = create_profile::CreateProfile::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PlayerProfileInstruction::CreateProfile(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = create_role::CreateRole::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PlayerProfileInstruction::CreateRole(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = invite_member_to_role::InviteMemberToRole::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PlayerProfileInstruction::InviteMemberToRole(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = join_role::JoinRole::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PlayerProfileInstruction::JoinRole(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = leave_role::LeaveRole::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PlayerProfileInstruction::LeaveRole(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = remove_keys::RemoveKeys::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PlayerProfileInstruction::RemoveKeys(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = remove_member_from_role::RemoveMemberFromRole::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PlayerProfileInstruction::RemoveMemberFromRole(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = remove_role::RemoveRole::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PlayerProfileInstruction::RemoveRole(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = set_name::SetName::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PlayerProfileInstruction::SetName(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = set_role_accepting_members::SetRoleAcceptingMembers::decode(data)
            {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PlayerProfileInstruction::SetRoleAcceptingMembers(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = set_role_authorizer::SetRoleAuthorizer::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PlayerProfileInstruction::SetRoleAuthorizer(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = set_role_name::SetRoleName::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PlayerProfileInstruction::SetRoleName(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) =
                set_role_not_accepting_members::SetRoleNotAcceptingMembers::decode(data)
            {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: PlayerProfileInstruction::SetRoleNotAcceptingMembers(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }

        None
    }
}
