//! This code was AUTOGENERATED using the Codama library.
use crate::types::AttackFleetInput;
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq, Eq, Hash)]
pub struct AttackFleet {
    pub input: AttackFleetInput,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct AttackFleetInstructionAccounts {
    pub key: solana_pubkey::Pubkey,
    pub owning_profile: solana_pubkey::Pubkey,
    pub owning_profile_faction: solana_pubkey::Pubkey,
    pub fleet: solana_pubkey::Pubkey,
    pub game_id: solana_pubkey::Pubkey,
    pub defending_fleet: solana_pubkey::Pubkey,
    pub attacking_cargo_pod: solana_pubkey::Pubkey,
    pub defending_cargo_pod: solana_pubkey::Pubkey,
    pub cargo_type: solana_pubkey::Pubkey,
    pub cargo_stats_definition: solana_pubkey::Pubkey,
    pub attacker_combat_xp: solana_pubkey::Pubkey,
    pub attacker_council_rank_xp: solana_pubkey::Pubkey,
    pub defender_combat_xp: solana_pubkey::Pubkey,
    pub defender_council_rank_xp: solana_pubkey::Pubkey,
    pub combat_xp_category: solana_pubkey::Pubkey,
    pub council_rank_xp_category: solana_pubkey::Pubkey,
    pub combat_xp_modifier: solana_pubkey::Pubkey,
    pub council_rank_xp_modifier: solana_pubkey::Pubkey,
    pub progression_config: solana_pubkey::Pubkey,
    pub combat_config: solana_pubkey::Pubkey,
    pub attacking_fleet_ammo_token: solana_pubkey::Pubkey,
    pub defending_fleet_ammo_token: solana_pubkey::Pubkey,
    pub token_mint: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl AttackFleet {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[89, 173, 5, 123, 109, 13, 236, 217] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for AttackFleet {
    type ArrangedAccounts = AttackFleetInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let key = next_account(&mut iter)?;
        let owning_profile = next_account(&mut iter)?;
        let owning_profile_faction = next_account(&mut iter)?;
        let fleet = next_account(&mut iter)?;
        let game_id = next_account(&mut iter)?;
        let defending_fleet = next_account(&mut iter)?;
        let attacking_cargo_pod = next_account(&mut iter)?;
        let defending_cargo_pod = next_account(&mut iter)?;
        let cargo_type = next_account(&mut iter)?;
        let cargo_stats_definition = next_account(&mut iter)?;
        let attacker_combat_xp = next_account(&mut iter)?;
        let attacker_council_rank_xp = next_account(&mut iter)?;
        let defender_combat_xp = next_account(&mut iter)?;
        let defender_council_rank_xp = next_account(&mut iter)?;
        let combat_xp_category = next_account(&mut iter)?;
        let council_rank_xp_category = next_account(&mut iter)?;
        let combat_xp_modifier = next_account(&mut iter)?;
        let council_rank_xp_modifier = next_account(&mut iter)?;
        let progression_config = next_account(&mut iter)?;
        let combat_config = next_account(&mut iter)?;
        let attacking_fleet_ammo_token = next_account(&mut iter)?;
        let defending_fleet_ammo_token = next_account(&mut iter)?;
        let token_mint = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(AttackFleetInstructionAccounts {
            key,
            owning_profile,
            owning_profile_faction,
            fleet,
            game_id,
            defending_fleet,
            attacking_cargo_pod,
            defending_cargo_pod,
            cargo_type,
            cargo_stats_definition,
            attacker_combat_xp,
            attacker_council_rank_xp,
            defender_combat_xp,
            defender_council_rank_xp,
            combat_xp_category,
            council_rank_xp_category,
            combat_xp_modifier,
            council_rank_xp_modifier,
            progression_config,
            combat_config,
            attacking_fleet_ammo_token,
            defending_fleet_ammo_token,
            token_mint,
            remaining: remaining.to_vec(),
        })
    }
}
