//! This code was AUTOGENERATED using the Codama library.
use crate::types::RegisterSagePointsModifierInput;
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq, Eq, Hash)]
pub struct RegisterSagePointModifier {
    pub input: RegisterSagePointsModifierInput,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct RegisterSagePointModifierInstructionAccounts {
    pub key: solana_pubkey::Pubkey,
    pub profile: solana_pubkey::Pubkey,
    pub game_id: solana_pubkey::Pubkey,
    pub funder: solana_pubkey::Pubkey,
    pub points_category: solana_pubkey::Pubkey,
    pub points_modifier: solana_pubkey::Pubkey,
    pub points_program: solana_pubkey::Pubkey,
    pub system_program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl RegisterSagePointModifier {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[212, 251, 164, 180, 158, 19, 173, 22] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for RegisterSagePointModifier {
    type ArrangedAccounts = RegisterSagePointModifierInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let key = next_account(&mut iter)?;
        let profile = next_account(&mut iter)?;
        let game_id = next_account(&mut iter)?;
        let funder = next_account(&mut iter)?;
        let points_category = next_account(&mut iter)?;
        let points_modifier = next_account(&mut iter)?;
        let points_program = next_account(&mut iter)?;
        let system_program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(RegisterSagePointModifierInstructionAccounts {
            key,
            profile,
            game_id,
            funder,
            points_category,
            points_modifier,
            points_program,
            system_program,
            remaining: remaining.to_vec(),
        })
    }
}
