//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
/// Struct for data add points category level

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct AddPointCategoryLevelInput {
    /// the level
    pub level: u16,
    /// the amount of points required for this level
    pub points: u64,
    /// the quantity of tokens required for this level
    pub token_qty: Option<u64>,
    /// the type of license
    pub license: u8,
    /// the index of the key in the player profile
    pub key_index: u16,
}
