//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
/// Struct for data input to remove points category level

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct RemovePointCategoryLevelInput {
    /// the index of the level in the array
    pub level_index: u16,
    /// the index of the key in the player profile
    pub key_index: u16,
}
