//! This code was AUTOGENERATED using the Codama library.
use crate::types::graphql::OrderSideGraphQL;
use carbon_core::graphql::primitives::I64;
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "OrderAccount")]
pub struct OrderAccountGraphQL {
    pub account_metadata: crate::accounts::graphql::AccountMetadataGraphQL,
    pub order_initializer_pubkey: Pubkey,
    pub currency_mint: Pubkey,
    pub asset_mint: Pubkey,
    pub initializer_currency_token_account: Pubkey,
    pub initializer_asset_token_account: Pubkey,
    pub order_side: OrderSideGraphQL,
    pub price: U64,
    pub order_origination_qty: U64,
    pub order_remaining_qty: U64,
    pub created_at_timestamp: I64,
}

impl TryFrom<crate::accounts::postgres::OrderAccountRow> for OrderAccountGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::accounts::postgres::OrderAccountRow) -> Result<Self, Self::Error> {
        Ok(Self {
            account_metadata: row.account_metadata.into(),
            order_initializer_pubkey: carbon_core::graphql::primitives::Pubkey(
                row.order_initializer_pubkey.0,
            ),
            currency_mint: carbon_core::graphql::primitives::Pubkey(row.currency_mint.0),
            asset_mint: carbon_core::graphql::primitives::Pubkey(row.asset_mint.0),
            initializer_currency_token_account: carbon_core::graphql::primitives::Pubkey(
                row.initializer_currency_token_account.0,
            ),
            initializer_asset_token_account: carbon_core::graphql::primitives::Pubkey(
                row.initializer_asset_token_account.0,
            ),
            order_side: row.order_side.0.into(),
            price: carbon_core::graphql::primitives::U64(*row.price),
            order_origination_qty: carbon_core::graphql::primitives::U64(
                *row.order_origination_qty,
            ),
            order_remaining_qty: carbon_core::graphql::primitives::U64(*row.order_remaining_qty),
            created_at_timestamp: carbon_core::graphql::primitives::I64(row.created_at_timestamp),
        })
    }
}
