//! This code was AUTOGENERATED using the Codama library.
pub mod craftable_item_row;
pub mod crafting_facility_row;
pub mod crafting_process_row;
pub mod domain_row;
pub mod recipe_category_row;
pub mod recipe_row;

pub use self::craftable_item_row::*;
pub use self::crafting_facility_row::*;
pub use self::crafting_process_row::*;
pub use self::domain_row::*;
pub use self::recipe_category_row::*;
pub use self::recipe_row::*;

use super::CraftingAccount;

pub struct CraftingAccountsMigration;

impl sqlx_migrator::Migration<sqlx::Postgres> for CraftingAccountsMigration {
    fn app(&self) -> &str {
        "crafting"
    }

    fn name(&self) -> &str {
        "crafting_accounts"
    }

    fn operations(&self) -> Vec<Box<dyn sqlx_migrator::Operation<sqlx::Postgres>>> {
        vec![
            Box::new(CraftableItemMigrationOperation),
            Box::new(CraftingFacilityMigrationOperation),
            Box::new(CraftingProcessMigrationOperation),
            Box::new(DomainMigrationOperation),
            Box::new(RecipeMigrationOperation),
            Box::new(RecipeCategoryMigrationOperation),
        ]
    }

    fn parents(&self) -> Vec<Box<dyn sqlx_migrator::Migration<sqlx::Postgres>>> {
        vec![]
    }
}

pub struct CraftingAccountWithMetadata(
    pub CraftingAccount,
    pub carbon_core::account::AccountMetadata,
);

impl From<(CraftingAccount, carbon_core::account::AccountMetadata)>
    for CraftingAccountWithMetadata
{
    fn from(value: (CraftingAccount, carbon_core::account::AccountMetadata)) -> Self {
        CraftingAccountWithMetadata(value.0, value.1)
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for CraftingAccountWithMetadata {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        let CraftingAccountWithMetadata(account, metadata) = self;

        match account {
            CraftingAccount::CraftableItem(account) => {
                let row = craftable_item_row::CraftableItemRow::from_parts(
                    *account.clone(),
                    metadata.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            CraftingAccount::CraftingFacility(account) => {
                let row = crafting_facility_row::CraftingFacilityRow::from_parts(
                    *account.clone(),
                    metadata.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            CraftingAccount::CraftingProcess(account) => {
                let row = crafting_process_row::CraftingProcessRow::from_parts(
                    *account.clone(),
                    metadata.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            CraftingAccount::Domain(account) => {
                let row = domain_row::DomainRow::from_parts(*account.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            CraftingAccount::Recipe(account) => {
                let row = recipe_row::RecipeRow::from_parts(*account.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            CraftingAccount::RecipeCategory(account) => {
                let row = recipe_category_row::RecipeCategoryRow::from_parts(
                    *account.clone(),
                    metadata.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
        }
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for CraftingAccountWithMetadata {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        let CraftingAccountWithMetadata(account, metadata) = self;
        match account {
            CraftingAccount::CraftableItem(account) => {
                let row = craftable_item_row::CraftableItemRow::from_parts(
                    *account.clone(),
                    metadata.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            CraftingAccount::CraftingFacility(account) => {
                let row = crafting_facility_row::CraftingFacilityRow::from_parts(
                    *account.clone(),
                    metadata.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            CraftingAccount::CraftingProcess(account) => {
                let row = crafting_process_row::CraftingProcessRow::from_parts(
                    *account.clone(),
                    metadata.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            CraftingAccount::Domain(account) => {
                let row = domain_row::DomainRow::from_parts(*account.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            CraftingAccount::Recipe(account) => {
                let row = recipe_row::RecipeRow::from_parts(*account.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            CraftingAccount::RecipeCategory(account) => {
                let row = recipe_category_row::RecipeCategoryRow::from_parts(
                    *account.clone(),
                    metadata.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
        }
    }
}
