//! This code was AUTOGENERATED using the Codama library.
use crate::types::graphql::BurnConsumableIngredientInputGraphQL;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "BurnConsumableIngredient")]
pub struct BurnConsumableIngredientGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub input: BurnConsumableIngredientInputGraphQL,
}

impl TryFrom<crate::instructions::postgres::BurnConsumableIngredientRow>
    for BurnConsumableIngredientGraphQL
{
    type Error = carbon_core::error::Error;
    fn try_from(
        row: crate::instructions::postgres::BurnConsumableIngredientRow,
    ) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            input: row.input.0.into(),
        })
    }
}
