//! This code was AUTOGENERATED using the Codama library.
use crate::types::graphql::ClaimNonConsumableIngredientInputGraphQL;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "ClaimNonConsumableIngredient")]
pub struct ClaimNonConsumableIngredientGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub input: ClaimNonConsumableIngredientInputGraphQL,
}

impl TryFrom<crate::instructions::postgres::ClaimNonConsumableIngredientRow>
    for ClaimNonConsumableIngredientGraphQL
{
    type Error = carbon_core::error::Error;
    fn try_from(
        row: crate::instructions::postgres::ClaimNonConsumableIngredientRow,
    ) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            input: row.input.0.into(),
        })
    }
}
