//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;

/// Cancels an ongoing rental before its scheduled end, marking it as canceled for repayment logic.

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq, Eq, Hash)]
pub struct CancelRental {}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CancelRentalInstructionAccounts {
    pub borrower: solana_pubkey::Pubkey,
    pub rental_thread: solana_pubkey::Pubkey,
    pub contract: solana_pubkey::Pubkey,
    pub rental_state: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl CancelRental {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[97, 204, 63, 8, 84, 34, 28, 43] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for CancelRental {
    type ArrangedAccounts = CancelRentalInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let borrower = next_account(&mut iter)?;
        let rental_thread = next_account(&mut iter)?;
        let contract = next_account(&mut iter)?;
        let rental_state = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(CancelRentalInstructionAccounts {
            borrower,
            rental_thread,
            contract,
            rental_state,
            remaining: remaining.to_vec(),
        })
    }
}
