//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::borsh;
use carbon_core::deserialize::CarbonDeserialize;
use solana_pubkey::Pubkey;

/// records rewards state on a user.

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct ProxyEscrow {
    /// The key of the account that is authorized to withdraw from the [Treasury].
    pub escrow_owner: Pubkey,
    /// Bump seed.
    pub bump: u8,
    /// Amount of tokens staked.
    pub amount: u64,
    /// When the [proxy_escrow::escrow_owner] started their escrow.
    pub escrow_started_at: i64,
    /// When the escrow unlocks; i.e. the [proxy_escrow::escrow_owner] is scheduled to be allowed to withdraw their governance tokens.
    pub escrow_ends_at: i64,
    /// When the [proxy_escrow::escrow_owner] last claimed rewards from [Treasury].
    pub rewards_last_claimed_at: i64,
    /// Amount of tokens claimed.
    pub amount_claimed: u64,
}

impl ProxyEscrow {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[59, 236, 59, 197, 113, 229, 79, 237] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}
