//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct ProcessInitializeSellPda {
    pub price: u64,
    pub origination_qty: u64,
    pub order_account_pubkey: Pubkey,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ProcessInitializeSellPdaInstructionAccounts {
    pub payer: solana_pubkey::Pubkey,
    pub order_initializer: solana_pubkey::Pubkey,
    pub market_vars_account: solana_pubkey::Pubkey,
    pub deposit_mint: solana_pubkey::Pubkey,
    pub receive_mint: solana_pubkey::Pubkey,
    pub order_vault_account: solana_pubkey::Pubkey,
    pub order_vault_authority: solana_pubkey::Pubkey,
    pub initializer_deposit_token_account: solana_pubkey::Pubkey,
    pub initializer_receive_token_account: solana_pubkey::Pubkey,
    pub order_account: solana_pubkey::Pubkey,
    pub registered_currency: solana_pubkey::Pubkey,
    pub open_orders_counter: solana_pubkey::Pubkey,
    pub system_program: solana_pubkey::Pubkey,
    pub rent: solana_pubkey::Pubkey,
    pub token_program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl ProcessInitializeSellPda {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[130, 184, 13, 176, 71, 35, 130, 56] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for ProcessInitializeSellPda {
    type ArrangedAccounts = ProcessInitializeSellPdaInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let payer = next_account(&mut iter)?;
        let order_initializer = next_account(&mut iter)?;
        let market_vars_account = next_account(&mut iter)?;
        let deposit_mint = next_account(&mut iter)?;
        let receive_mint = next_account(&mut iter)?;
        let order_vault_account = next_account(&mut iter)?;
        let order_vault_authority = next_account(&mut iter)?;
        let initializer_deposit_token_account = next_account(&mut iter)?;
        let initializer_receive_token_account = next_account(&mut iter)?;
        let order_account = next_account(&mut iter)?;
        let registered_currency = next_account(&mut iter)?;
        let open_orders_counter = next_account(&mut iter)?;
        let system_program = next_account(&mut iter)?;
        let rent = next_account(&mut iter)?;
        let token_program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(ProcessInitializeSellPdaInstructionAccounts {
            payer,
            order_initializer,
            market_vars_account,
            deposit_mint,
            receive_mint,
            order_vault_account,
            order_vault_authority,
            initializer_deposit_token_account,
            initializer_receive_token_account,
            order_account,
            registered_currency,
            open_orders_counter,
            system_program,
            rent,
            token_program,
            remaining: remaining.to_vec(),
        })
    }
}
