//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq, Eq, Hash)]
pub struct RemoveFeeExemption {}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct RemoveFeeExemptionInstructionAccounts {
    pub update_authority_master: solana_pubkey::Pubkey,
    pub funder: solana_pubkey::Pubkey,
    pub market_vars_account: solana_pubkey::Pubkey,
    pub fee_exempt_account: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl RemoveFeeExemption {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[158, 59, 24, 139, 29, 141, 63, 15] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for RemoveFeeExemption {
    type ArrangedAccounts = RemoveFeeExemptionInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let update_authority_master = next_account(&mut iter)?;
        let funder = next_account(&mut iter)?;
        let market_vars_account = next_account(&mut iter)?;
        let fee_exempt_account = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(RemoveFeeExemptionInstructionAccounts {
            update_authority_master,
            funder,
            market_vars_account,
            fee_exempt_account,
            remaining: remaining.to_vec(),
        })
    }
}
