//! This code was AUTOGENERATED using the Codama library.
use solana_pubkey::Pubkey;
pub struct LockedVoterDecoder;
pub const PROGRAM_ID: Pubkey =
    solana_pubkey::Pubkey::from_str_const("Lock7kBijGCQLEFAmXcengzXKA88iDNQPriQ7TbgeyG");

pub mod accounts;
pub mod events;
pub mod instructions;
pub mod types;
