//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U8;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "VaultAuthority")]
pub struct VaultAuthorityGraphQL {
    pub account_metadata: crate::accounts::graphql::AccountMetadataGraphQL,
    pub version: U8,
    pub profile: Pubkey,
    pub vault_seed: Pubkey,
    pub vault_bump: U8,
}

impl TryFrom<crate::accounts::postgres::VaultAuthorityRow> for VaultAuthorityGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::accounts::postgres::VaultAuthorityRow) -> Result<Self, Self::Error> {
        Ok(Self {
            account_metadata: row.account_metadata.into(),
            version: carbon_core::graphql::primitives::U8((*row.version) as u8),
            profile: carbon_core::graphql::primitives::Pubkey(row.profile.0),
            vault_seed: carbon_core::graphql::primitives::Pubkey(row.vault_seed.0),
            vault_bump: carbon_core::graphql::primitives::U8((*row.vault_bump) as u8),
        })
    }
}
