//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::I64;
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "LockWithWhitelistEntry")]
pub struct LockWithWhitelistEntryGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub amount: U64,
    pub duration: I64,
}

impl TryFrom<crate::instructions::postgres::LockWithWhitelistEntryRow>
    for LockWithWhitelistEntryGraphQL
{
    type Error = carbon_core::error::Error;
    fn try_from(
        row: crate::instructions::postgres::LockWithWhitelistEntryRow,
    ) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            amount: carbon_core::graphql::primitives::U64(*row.amount),
            duration: carbon_core::graphql::primitives::I64(row.duration),
        })
    }
}
