//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U8;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "NewEscrow")]
pub struct NewEscrowGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub bump: U8,
}

impl TryFrom<crate::instructions::postgres::NewEscrowRow> for NewEscrowGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::instructions::postgres::NewEscrowRow) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            bump: carbon_core::graphql::primitives::U8((*row.bump) as u8),
        })
    }
}
