//! This code was AUTOGENERATED using the Codama library.
use carbon_core::account::AccountMetadata;
use carbon_core::postgres::metadata::AccountRowMetadata;
use carbon_core::postgres::primitives::U64;

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct AtlasRateAccountRow {
    #[sqlx(flatten)]
    pub account_metadata: AccountRowMetadata,
    pub atlas_rate: U64,
}

impl AtlasRateAccountRow {
    pub fn from_parts(
        source: crate::accounts::atlas_rate_account::AtlasRateAccount,
        metadata: AccountMetadata,
    ) -> Self {
        Self {
            account_metadata: metadata.into(),
            atlas_rate: source.atlas_rate.into(),
        }
    }
}

impl TryFrom<AtlasRateAccountRow> for crate::accounts::atlas_rate_account::AtlasRateAccount {
    type Error = carbon_core::error::Error;
    fn try_from(source: AtlasRateAccountRow) -> Result<Self, Self::Error> {
        Ok(Self {
            atlas_rate: *source.atlas_rate,
        })
    }
}

impl carbon_core::postgres::operations::Table
    for crate::accounts::atlas_rate_account::AtlasRateAccount
{
    fn table() -> &'static str {
        "atlas_rate_account_account"
    }

    fn columns() -> Vec<&'static str> {
        vec!["__pubkey", "__slot", "atlas_rate"]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for AtlasRateAccountRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"
            INSERT INTO atlas_rate_account_account (
                "atlas_rate",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3
            )"#,
        )
        .bind(self.atlas_rate.clone())
        .bind(self.account_metadata.pubkey.clone())
        .bind(self.account_metadata.slot.clone())
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for AtlasRateAccountRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"INSERT INTO atlas_rate_account_account (
                "atlas_rate",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3
            ) ON CONFLICT (
                __pubkey
            ) DO UPDATE SET
                "atlas_rate" = EXCLUDED."atlas_rate",
                __slot = EXCLUDED.__slot
            "#,
        )
        .bind(self.atlas_rate.clone())
        .bind(self.account_metadata.pubkey)
        .bind(self.account_metadata.slot.clone())
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for AtlasRateAccountRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"DELETE FROM atlas_rate_account_account WHERE
                __pubkey = $1
            "#,
        )
        .bind(key)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for AtlasRateAccountRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn lookup(
        key: Self::Key,
        pool: &sqlx::PgPool,
    ) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(
            r#"SELECT * FROM atlas_rate_account_account WHERE
                __pubkey = $1
            "#,
        )
        .bind(key)
        .fetch_optional(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct AtlasRateAccountMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for AtlasRateAccountMigrationOperation {
    async fn up(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(
            r#"CREATE TABLE IF NOT EXISTS atlas_rate_account_account (
                -- Account data
                "atlas_rate" NUMERIC(20) NOT NULL,
                -- Account metadata
                __pubkey BYTEA NOT NULL,
                __slot NUMERIC(20),
                PRIMARY KEY (__pubkey)
            )"#,
        )
        .execute(connection)
        .await?;
        Ok(())
    }

    async fn down(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS atlas_rate_account_account"#)
            .execute(connection)
            .await?;
        Ok(())
    }
}
