//! This code was AUTOGENERATED using the Codama library.
pub mod atlas_rate_account_row;
pub mod fee_reduction_row;
pub mod market_vars_row;
pub mod open_orders_counter_row;
pub mod order_account_row;
pub mod registered_currency_row;

pub use self::atlas_rate_account_row::*;
pub use self::fee_reduction_row::*;
pub use self::market_vars_row::*;
pub use self::open_orders_counter_row::*;
pub use self::order_account_row::*;
pub use self::registered_currency_row::*;

use super::MarketplaceAccount;

pub struct MarketplaceAccountsMigration;

impl sqlx_migrator::Migration<sqlx::Postgres> for MarketplaceAccountsMigration {
    fn app(&self) -> &str {
        "marketplace"
    }

    fn name(&self) -> &str {
        "marketplace_accounts"
    }

    fn operations(&self) -> Vec<Box<dyn sqlx_migrator::Operation<sqlx::Postgres>>> {
        vec![
            Box::new(AtlasRateAccountMigrationOperation),
            Box::new(FeeReductionMigrationOperation),
            Box::new(MarketVarsMigrationOperation),
            Box::new(OpenOrdersCounterMigrationOperation),
            Box::new(OrderAccountMigrationOperation),
            Box::new(RegisteredCurrencyMigrationOperation),
        ]
    }

    fn parents(&self) -> Vec<Box<dyn sqlx_migrator::Migration<sqlx::Postgres>>> {
        vec![]
    }
}

pub struct MarketplaceAccountWithMetadata(
    pub MarketplaceAccount,
    pub carbon_core::account::AccountMetadata,
);

impl From<(MarketplaceAccount, carbon_core::account::AccountMetadata)>
    for MarketplaceAccountWithMetadata
{
    fn from(value: (MarketplaceAccount, carbon_core::account::AccountMetadata)) -> Self {
        MarketplaceAccountWithMetadata(value.0, value.1)
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for MarketplaceAccountWithMetadata {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        let MarketplaceAccountWithMetadata(account, metadata) = self;

        match account {
            MarketplaceAccount::AtlasRateAccount(account) => {
                let row = atlas_rate_account_row::AtlasRateAccountRow::from_parts(
                    *account.clone(),
                    metadata.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            MarketplaceAccount::FeeReduction(account) => {
                let row = fee_reduction_row::FeeReductionRow::from_parts(
                    *account.clone(),
                    metadata.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            MarketplaceAccount::MarketVars(account) => {
                let row =
                    market_vars_row::MarketVarsRow::from_parts(*account.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            MarketplaceAccount::OpenOrdersCounter(account) => {
                let row = open_orders_counter_row::OpenOrdersCounterRow::from_parts(
                    *account.clone(),
                    metadata.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            MarketplaceAccount::OrderAccount(account) => {
                let row = order_account_row::OrderAccountRow::from_parts(
                    *account.clone(),
                    metadata.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            MarketplaceAccount::RegisteredCurrency(account) => {
                let row = registered_currency_row::RegisteredCurrencyRow::from_parts(
                    *account.clone(),
                    metadata.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
        }
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for MarketplaceAccountWithMetadata {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        let MarketplaceAccountWithMetadata(account, metadata) = self;
        match account {
            MarketplaceAccount::AtlasRateAccount(account) => {
                let row = atlas_rate_account_row::AtlasRateAccountRow::from_parts(
                    *account.clone(),
                    metadata.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            MarketplaceAccount::FeeReduction(account) => {
                let row = fee_reduction_row::FeeReductionRow::from_parts(
                    *account.clone(),
                    metadata.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            MarketplaceAccount::MarketVars(account) => {
                let row =
                    market_vars_row::MarketVarsRow::from_parts(*account.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            MarketplaceAccount::OpenOrdersCounter(account) => {
                let row = open_orders_counter_row::OpenOrdersCounterRow::from_parts(
                    *account.clone(),
                    metadata.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            MarketplaceAccount::OrderAccount(account) => {
                let row = order_account_row::OrderAccountRow::from_parts(
                    *account.clone(),
                    metadata.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            MarketplaceAccount::RegisteredCurrency(account) => {
                let row = registered_currency_row::RegisteredCurrencyRow::from_parts(
                    *account.clone(),
                    metadata.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
        }
    }
}
