//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;

/// Registers a Locker from the locked_voter program

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq, Eq, Hash)]
pub struct RegisterLocker {}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct RegisterLockerInstructionAccounts {
    pub admin: solana_pubkey::Pubkey,
    pub locker: solana_pubkey::Pubkey,
    pub registered_locker: solana_pubkey::Pubkey,
    pub token_mint: solana_pubkey::Pubkey,
    pub treasury_token_account: solana_pubkey::Pubkey,
    pub treasury_authority: solana_pubkey::Pubkey,
    pub token_program: solana_pubkey::Pubkey,
    pub system_program: solana_pubkey::Pubkey,
    pub rent: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl RegisterLocker {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[86, 165, 215, 222, 1, 31, 88, 95] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for RegisterLocker {
    type ArrangedAccounts = RegisterLockerInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let admin = next_account(&mut iter)?;
        let locker = next_account(&mut iter)?;
        let registered_locker = next_account(&mut iter)?;
        let token_mint = next_account(&mut iter)?;
        let treasury_token_account = next_account(&mut iter)?;
        let treasury_authority = next_account(&mut iter)?;
        let token_program = next_account(&mut iter)?;
        let system_program = next_account(&mut iter)?;
        let rent = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(RegisterLockerInstructionAccounts {
            admin,
            locker,
            registered_locker,
            token_mint,
            treasury_token_account,
            treasury_authority,
            token_program,
            system_program,
            rent,
            remaining: remaining.to_vec(),
        })
    }
}
