//! This code was AUTOGENERATED using the Codama library.
use crate::PROGRAM_ID;
use crate::ProfileVaultDecoder;

pub mod close_vault;
pub mod create_vault_authority;
pub mod drain_vault;

pub use self::close_vault::*;
pub use self::create_vault_authority::*;
pub use self::drain_vault::*;

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[cfg_attr(
    feature = "serde",
    derive(carbon_core::InstructionType, serde::Serialize, serde::Deserialize)
)]
#[cfg_attr(feature = "serde", serde(tag = "type", content = "data"))]
pub enum ProfileVaultInstruction {
    CloseVault(CloseVault),
    CreateVaultAuthority(CreateVaultAuthority),
    DrainVault(DrainVault),
}

impl carbon_core::instruction::InstructionDecoder<'_> for ProfileVaultDecoder {
    type InstructionType = ProfileVaultInstruction;

    fn decode_instruction(
        &self,
        instruction: &solana_instruction::Instruction,
    ) -> Option<carbon_core::instruction::DecodedInstruction<Self::InstructionType>> {
        if !instruction.program_id.eq(&PROGRAM_ID) {
            return None;
        }

        let data = instruction.data.as_slice();

        {
            if let Some(decoded) = close_vault::CloseVault::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: ProfileVaultInstruction::CloseVault(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = create_vault_authority::CreateVaultAuthority::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: ProfileVaultInstruction::CreateVaultAuthority(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = drain_vault::DrainVault::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: ProfileVaultInstruction::DrainVault(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }

        None
    }
}
