//! This code was AUTOGENERATED using the Codama library.
use carbon_core::instruction::InstructionMetadata;
use carbon_core::postgres::metadata::InstructionRowMetadata;
use carbon_core::postgres::primitives::U16;

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct AcceptRoleInvitationRow {
    #[sqlx(flatten)]
    pub instruction_metadata: InstructionRowMetadata,
    pub key_index: U16,
    pub key_index_in_role_account: U16,
    pub key_index_in_membership_account: U16,
}

impl AcceptRoleInvitationRow {
    pub fn from_parts(
        source: crate::instructions::accept_role_invitation::AcceptRoleInvitation,
        metadata: InstructionMetadata,
    ) -> Self {
        Self {
            instruction_metadata: metadata.into(),
            key_index: source.key_index.into(),
            key_index_in_role_account: source.key_index_in_role_account.into(),
            key_index_in_membership_account: source.key_index_in_membership_account.into(),
        }
    }
}

impl TryFrom<AcceptRoleInvitationRow>
    for crate::instructions::accept_role_invitation::AcceptRoleInvitation
{
    type Error = carbon_core::error::Error;
    fn try_from(source: AcceptRoleInvitationRow) -> Result<Self, Self::Error> {
        Ok(Self {
            key_index: source.key_index.try_into().map_err(|_| {
                carbon_core::error::Error::Custom(
                    "Failed to convert value from postgres primitive".to_string(),
                )
            })?,
            key_index_in_role_account: source.key_index_in_role_account.try_into().map_err(
                |_| {
                    carbon_core::error::Error::Custom(
                        "Failed to convert value from postgres primitive".to_string(),
                    )
                },
            )?,
            key_index_in_membership_account: source
                .key_index_in_membership_account
                .try_into()
                .map_err(|_| {
                    carbon_core::error::Error::Custom(
                        "Failed to convert value from postgres primitive".to_string(),
                    )
                })?,
        })
    }
}

impl carbon_core::postgres::operations::Table
    for crate::instructions::accept_role_invitation::AcceptRoleInvitation
{
    fn table() -> &'static str {
        "accept_role_invitation_instruction"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__signature",
            "__instruction_index",
            "__stack_height",
            "__slot",
            "key_index",
            "key_index_in_role_account",
            "key_index_in_membership_account",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for AcceptRoleInvitationRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"
            INSERT INTO accept_role_invitation_instruction (
                "key_index",
                "key_index_in_role_account",
                "key_index_in_membership_account",
                __signature, __instruction_index, __stack_height, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7
            )"#,
        )
        .bind(self.key_index.clone())
        .bind(self.key_index_in_role_account.clone())
        .bind(self.key_index_in_membership_account.clone())
        .bind(self.instruction_metadata.signature.clone())
        .bind(self.instruction_metadata.instruction_index.clone())
        .bind(self.instruction_metadata.stack_height.clone())
        .bind(self.instruction_metadata.slot.clone())
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for AcceptRoleInvitationRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"INSERT INTO accept_role_invitation_instruction (
                "key_index",
                "key_index_in_role_account",
                "key_index_in_membership_account",
                __signature, __instruction_index, __stack_height, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7
            ) ON CONFLICT (
                __signature, __instruction_index, __stack_height
            ) DO UPDATE SET
                "key_index" = EXCLUDED."key_index",
                "key_index_in_role_account" = EXCLUDED."key_index_in_role_account",
                "key_index_in_membership_account" = EXCLUDED."key_index_in_membership_account",
                __instruction_index = EXCLUDED.__instruction_index,
                __stack_height = EXCLUDED.__stack_height,
                __slot = EXCLUDED.__slot
            "#,
        )
        .bind(self.key_index.clone())
        .bind(self.key_index_in_role_account.clone())
        .bind(self.key_index_in_membership_account.clone())
        .bind(self.instruction_metadata.signature.clone())
        .bind(self.instruction_metadata.instruction_index.clone())
        .bind(self.instruction_metadata.stack_height.clone())
        .bind(self.instruction_metadata.slot.clone())
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for AcceptRoleInvitationRow {
    type Key = (
        String,
        carbon_core::postgres::primitives::U32,
        carbon_core::postgres::primitives::U32,
    );

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"DELETE FROM accept_role_invitation_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#,
        )
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for AcceptRoleInvitationRow {
    type Key = (
        String,
        carbon_core::postgres::primitives::U32,
        carbon_core::postgres::primitives::U32,
    );

    async fn lookup(
        key: Self::Key,
        pool: &sqlx::PgPool,
    ) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(
            r#"SELECT * FROM accept_role_invitation_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#,
        )
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .fetch_optional(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct AcceptRoleInvitationMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for AcceptRoleInvitationMigrationOperation {
    async fn up(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(
            r#"CREATE TABLE IF NOT EXISTS accept_role_invitation_instruction (
                -- Instruction data
                "key_index" INT4 NOT NULL,
                "key_index_in_role_account" INT4 NOT NULL,
                "key_index_in_membership_account" INT4 NOT NULL,
                -- Instruction metadata
                __signature TEXT NOT NULL,
                __instruction_index BIGINT NOT NULL,
                __stack_height BIGINT NOT NULL,
                __slot NUMERIC(20),
                PRIMARY KEY (__signature, __instruction_index, __stack_height)
            )"#,
        )
        .execute(connection)
        .await?;
        Ok(())
    }

    async fn down(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS accept_role_invitation_instruction"#)
            .execute(connection)
            .await?;
        Ok(())
    }
}
