//! This code was AUTOGENERATED using the Codama library.
use crate::types::AddKeyInput;
use carbon_core::instruction::InstructionMetadata;
use carbon_core::postgres::metadata::InstructionRowMetadata;
use carbon_core::postgres::primitives::U16;

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct AddKeysRow {
    #[sqlx(flatten)]
    pub instruction_metadata: InstructionRowMetadata,
    pub key_add_index: U16,
    pub key_permissions_index: U16,
    pub keys_to_add: sqlx::types::Json<Vec<AddKeyInput>>,
}

impl AddKeysRow {
    pub fn from_parts(
        source: crate::instructions::add_keys::AddKeys,
        metadata: InstructionMetadata,
    ) -> Self {
        Self {
            instruction_metadata: metadata.into(),
            key_add_index: source.key_add_index.into(),
            key_permissions_index: source.key_permissions_index.into(),
            keys_to_add: sqlx::types::Json(
                source
                    .keys_to_add
                    .into_iter()
                    .map(|element| element.into())
                    .collect(),
            ),
        }
    }
}

impl TryFrom<AddKeysRow> for crate::instructions::add_keys::AddKeys {
    type Error = carbon_core::error::Error;
    fn try_from(source: AddKeysRow) -> Result<Self, Self::Error> {
        Ok(Self {
            key_add_index: source.key_add_index.try_into().map_err(|_| {
                carbon_core::error::Error::Custom(
                    "Failed to convert value from postgres primitive".to_string(),
                )
            })?,
            key_permissions_index: source.key_permissions_index.try_into().map_err(|_| {
                carbon_core::error::Error::Custom(
                    "Failed to convert value from postgres primitive".to_string(),
                )
            })?,
            keys_to_add: source.keys_to_add.0,
        })
    }
}

impl carbon_core::postgres::operations::Table for crate::instructions::add_keys::AddKeys {
    fn table() -> &'static str {
        "add_keys_instruction"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__signature",
            "__instruction_index",
            "__stack_height",
            "__slot",
            "key_add_index",
            "key_permissions_index",
            "keys_to_add",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for AddKeysRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"
            INSERT INTO add_keys_instruction (
                "key_add_index",
                "key_permissions_index",
                "keys_to_add",
                __signature, __instruction_index, __stack_height, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7
            )"#,
        )
        .bind(self.key_add_index.clone())
        .bind(self.key_permissions_index.clone())
        .bind(self.keys_to_add.clone())
        .bind(self.instruction_metadata.signature.clone())
        .bind(self.instruction_metadata.instruction_index.clone())
        .bind(self.instruction_metadata.stack_height.clone())
        .bind(self.instruction_metadata.slot.clone())
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for AddKeysRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"INSERT INTO add_keys_instruction (
                "key_add_index",
                "key_permissions_index",
                "keys_to_add",
                __signature, __instruction_index, __stack_height, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7
            ) ON CONFLICT (
                __signature, __instruction_index, __stack_height
            ) DO UPDATE SET
                "key_add_index" = EXCLUDED."key_add_index",
                "key_permissions_index" = EXCLUDED."key_permissions_index",
                "keys_to_add" = EXCLUDED."keys_to_add",
                __instruction_index = EXCLUDED.__instruction_index,
                __stack_height = EXCLUDED.__stack_height,
                __slot = EXCLUDED.__slot
            "#,
        )
        .bind(self.key_add_index.clone())
        .bind(self.key_permissions_index.clone())
        .bind(self.keys_to_add.clone())
        .bind(self.instruction_metadata.signature.clone())
        .bind(self.instruction_metadata.instruction_index.clone())
        .bind(self.instruction_metadata.stack_height.clone())
        .bind(self.instruction_metadata.slot.clone())
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for AddKeysRow {
    type Key = (
        String,
        carbon_core::postgres::primitives::U32,
        carbon_core::postgres::primitives::U32,
    );

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"DELETE FROM add_keys_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#,
        )
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for AddKeysRow {
    type Key = (
        String,
        carbon_core::postgres::primitives::U32,
        carbon_core::postgres::primitives::U32,
    );

    async fn lookup(
        key: Self::Key,
        pool: &sqlx::PgPool,
    ) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(
            r#"SELECT * FROM add_keys_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#,
        )
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .fetch_optional(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct AddKeysMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for AddKeysMigrationOperation {
    async fn up(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(
            r#"CREATE TABLE IF NOT EXISTS add_keys_instruction (
                -- Instruction data
                "key_add_index" INT4 NOT NULL,
                "key_permissions_index" INT4 NOT NULL,
                "keys_to_add" JSONB NOT NULL,
                -- Instruction metadata
                __signature TEXT NOT NULL,
                __instruction_index BIGINT NOT NULL,
                __stack_height BIGINT NOT NULL,
                __slot NUMERIC(20),
                PRIMARY KEY (__signature, __instruction_index, __stack_height)
            )"#,
        )
        .execute(connection)
        .await?;
        Ok(())
    }

    async fn down(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS add_keys_instruction"#)
            .execute(connection)
            .await?;
        Ok(())
    }
}
