//! This code was AUTOGENERATED using the Codama library.
use crate::types::AddKeyInput;
use carbon_core::instruction::InstructionMetadata;
use carbon_core::postgres::metadata::InstructionRowMetadata;
use carbon_core::postgres::primitives::U8;
use carbon_core::postgres::primitives::U16;

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct AdjustAuthRow {
    #[sqlx(flatten)]
    pub instruction_metadata: InstructionRowMetadata,
    pub auth_indexes: Vec<U16>,
    pub new_key_permissions: sqlx::types::Json<Vec<AddKeyInput>>,
    pub remove_range: Vec<U16>,
    pub new_key_threshold: U8,
}

impl AdjustAuthRow {
    pub fn from_parts(
        source: crate::instructions::adjust_auth::AdjustAuth,
        metadata: InstructionMetadata,
    ) -> Self {
        Self {
            instruction_metadata: metadata.into(),
            auth_indexes: source
                .auth_indexes
                .into_iter()
                .map(|element| element.into())
                .collect(),
            new_key_permissions: sqlx::types::Json(
                source
                    .new_key_permissions
                    .into_iter()
                    .map(|element| element.into())
                    .collect(),
            ),
            remove_range: source
                .remove_range
                .into_iter()
                .map(|element| element.into())
                .collect(),
            new_key_threshold: source.new_key_threshold.into(),
        }
    }
}

impl TryFrom<AdjustAuthRow> for crate::instructions::adjust_auth::AdjustAuth {
    type Error = carbon_core::error::Error;
    fn try_from(source: AdjustAuthRow) -> Result<Self, Self::Error> {
        Ok(Self {
            auth_indexes: source
                .auth_indexes
                .into_iter()
                .map(|element| element.try_into())
                .collect::<Result<_, _>>()
                .map_err(|_| {
                    carbon_core::error::Error::Custom(
                        "Failed to convert array element to primitive".to_string(),
                    )
                })?,
            new_key_permissions: source.new_key_permissions.0,
            remove_range: source
                .remove_range
                .into_iter()
                .map(|element| {
                    Ok(element.try_into().map_err(|_| {
                        carbon_core::error::Error::Custom(
                            "Failed to convert value from postgres primitive".to_string(),
                        )
                    })?)
                })
                .collect::<Result<Vec<_>, _>>()?
                .try_into()
                .map_err(|_| {
                    carbon_core::error::Error::Custom(
                        "Failed to convert array element to primitive".to_string(),
                    )
                })?,
            new_key_threshold: source.new_key_threshold.try_into().map_err(|_| {
                carbon_core::error::Error::Custom(
                    "Failed to convert value from postgres primitive".to_string(),
                )
            })?,
        })
    }
}

impl carbon_core::postgres::operations::Table for crate::instructions::adjust_auth::AdjustAuth {
    fn table() -> &'static str {
        "adjust_auth_instruction"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__signature",
            "__instruction_index",
            "__stack_height",
            "__slot",
            "auth_indexes",
            "new_key_permissions",
            "remove_range",
            "new_key_threshold",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for AdjustAuthRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"
            INSERT INTO adjust_auth_instruction (
                "auth_indexes",
                "new_key_permissions",
                "remove_range",
                "new_key_threshold",
                __signature, __instruction_index, __stack_height, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8
            )"#,
        )
        .bind(self.auth_indexes.clone())
        .bind(self.new_key_permissions.clone())
        .bind(self.remove_range.clone())
        .bind(self.new_key_threshold.clone())
        .bind(self.instruction_metadata.signature.clone())
        .bind(self.instruction_metadata.instruction_index.clone())
        .bind(self.instruction_metadata.stack_height.clone())
        .bind(self.instruction_metadata.slot.clone())
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for AdjustAuthRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"INSERT INTO adjust_auth_instruction (
                "auth_indexes",
                "new_key_permissions",
                "remove_range",
                "new_key_threshold",
                __signature, __instruction_index, __stack_height, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8
            ) ON CONFLICT (
                __signature, __instruction_index, __stack_height
            ) DO UPDATE SET
                "auth_indexes" = EXCLUDED."auth_indexes",
                "new_key_permissions" = EXCLUDED."new_key_permissions",
                "remove_range" = EXCLUDED."remove_range",
                "new_key_threshold" = EXCLUDED."new_key_threshold",
                __instruction_index = EXCLUDED.__instruction_index,
                __stack_height = EXCLUDED.__stack_height,
                __slot = EXCLUDED.__slot
            "#,
        )
        .bind(self.auth_indexes.clone())
        .bind(self.new_key_permissions.clone())
        .bind(self.remove_range.clone())
        .bind(self.new_key_threshold.clone())
        .bind(self.instruction_metadata.signature.clone())
        .bind(self.instruction_metadata.instruction_index.clone())
        .bind(self.instruction_metadata.stack_height.clone())
        .bind(self.instruction_metadata.slot.clone())
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for AdjustAuthRow {
    type Key = (
        String,
        carbon_core::postgres::primitives::U32,
        carbon_core::postgres::primitives::U32,
    );

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"DELETE FROM adjust_auth_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#,
        )
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for AdjustAuthRow {
    type Key = (
        String,
        carbon_core::postgres::primitives::U32,
        carbon_core::postgres::primitives::U32,
    );

    async fn lookup(
        key: Self::Key,
        pool: &sqlx::PgPool,
    ) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(
            r#"SELECT * FROM adjust_auth_instruction WHERE
                __signature = $1 AND __instruction_index = $2 AND __stack_height = $3
            "#,
        )
        .bind(key.0)
        .bind(key.1)
        .bind(key.2)
        .fetch_optional(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct AdjustAuthMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for AdjustAuthMigrationOperation {
    async fn up(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(
            r#"CREATE TABLE IF NOT EXISTS adjust_auth_instruction (
                -- Instruction data
                "auth_indexes" INT4[] NOT NULL,
                "new_key_permissions" JSONB NOT NULL,
                "remove_range" INT4[] NOT NULL,
                "new_key_threshold" INT2 NOT NULL,
                -- Instruction metadata
                __signature TEXT NOT NULL,
                __instruction_index BIGINT NOT NULL,
                __stack_height BIGINT NOT NULL,
                __slot NUMERIC(20),
                PRIMARY KEY (__signature, __instruction_index, __stack_height)
            )"#,
        )
        .execute(connection)
        .await?;
        Ok(())
    }

    async fn down(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS adjust_auth_instruction"#)
            .execute(connection)
            .await?;
        Ok(())
    }
}
