//! This code was AUTOGENERATED using the Codama library.
use crate::types::graphql::CreatePointsStoreInputUnpackedGraphQL;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "CreatePointsStore")]
pub struct CreatePointsStoreGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub input: CreatePointsStoreInputUnpackedGraphQL,
}

impl TryFrom<crate::instructions::postgres::CreatePointsStoreRow> for CreatePointsStoreGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(
        row: crate::instructions::postgres::CreatePointsStoreRow,
    ) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            input: row.input.0.into(),
        })
    }
}
