//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "RemoveStoreItems")]
pub struct RemoveStoreItemsGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub amount: U64,
    pub key_index: i32,
}

impl TryFrom<crate::instructions::postgres::RemoveStoreItemsRow> for RemoveStoreItemsGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(
        row: crate::instructions::postgres::RemoveStoreItemsRow,
    ) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            amount: carbon_core::graphql::primitives::U64(*row.amount),
            key_index: (*row.key_index) as i32,
        })
    }
}
