//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct CreateFeePayerRates {
    pub token_limit: u64,
    pub conversion_rate: u64,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CreateFeePayerRatesInstructionAccounts {
    pub rates: solana_pubkey::Pubkey,
    pub funder: solana_pubkey::Pubkey,
    pub owning_profile: solana_pubkey::Pubkey,
    pub token_mint: solana_pubkey::Pubkey,
    pub token_owner: solana_pubkey::Pubkey,
    pub system_program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl CreateFeePayerRates {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[23, 20, 200, 129, 126, 92, 108, 107] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for CreateFeePayerRates {
    type ArrangedAccounts = CreateFeePayerRatesInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let rates = next_account(&mut iter)?;
        let funder = next_account(&mut iter)?;
        let owning_profile = next_account(&mut iter)?;
        let token_mint = next_account(&mut iter)?;
        let token_owner = next_account(&mut iter)?;
        let system_program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(CreateFeePayerRatesInstructionAccounts {
            rates,
            funder,
            owning_profile,
            token_mint,
            token_owner,
            system_program,
            remaining: remaining.to_vec(),
        })
    }
}
