//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
/// The input for the `redeem_crew_packs` instruction.

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq, Eq, Hash)]
pub struct MintCrewMemberInput {
    /// The index of the key in the profile's permissions list
    pub key_index: u16,
    /// The index of the crew member in the `UserRedemption` account
    pub user_redemption_index: u32,
    /// The hash of the off chain data
    pub data_hash: [u8; 16],
}
