//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
use solana_pubkey::Pubkey;
/// Input for redeeming crew packs via `RedeemCrewPacks`

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct RedeemCrewPacksInput {
    /// The number of crew pack SFTs to redeem
    pub quantity: u32,
    /// A pubkey to use as a seed for the `UserRedemption` account
    pub seed_pubkey: Pubkey,
    /// Server provided sha256 hash of a random pubkey preimage used during minting
    pub server_hash: [u8; 32],
    /// The index of the profile_key in the profile's permission list
    pub key_index: u16,
    /// Optional SagePlayerProfile key for minting directly to sage
    pub sage_profile: Option<Pubkey>,
}
