//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
/// The 5 crew assignment states. Stored on-chain as the raw `u8` `tag` of `CrewStatus`
/// (kept a `u8`, not this enum, to preserve the `Pod`-ness of `CrewRecord`). AtStarbase /
/// OnFleet / Busy count as "present"; Respawning / Dead do not.

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq, Eq, Hash)]
pub enum CrewStatusTag {
    AtStarbase,
    OnFleet,
    Busy,
    Respawning,
    Dead,
}
