//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
/// A ship's movement stats

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct MovementStats {
    /// the amount of distance that the ship can cover in one second while sub-warping
    pub subwarp_speed: u32,
    /// the amount of distance that the ship can cover in one second while warping
    pub warp_speed: u32,
    /// the max distance that the ship can warp
    pub max_warp_distance: u16,
    /// the time it takes the ship to be able to warp again after a warp
    pub warp_cool_down: u16,
    /// the amount of fuel consumed by the ship when sub-warp moving
    pub subwarp_fuel_consumption_rate: u32,
    /// the amount of fuel consumed by the ship when warp moving
    pub warp_fuel_consumption_rate: u32,
    /// the amount of fuel required to exit a planet
    pub planet_exit_fuel_amount: u32,
}
