//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
/// Struct for data input to Register `Starbase`

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct RegisterStarbaseInput {
    /// `Starbase` name
    pub name: Vec<u8>,
    /// `Starbase` coordinates
    pub sub_coordinates: [i64; 2],
    /// The index representing the level of the `Starbase` in the game variables.
    pub starbase_level_index: u8,
    /// The `Starbase` faction
    pub faction: u8,
    /// the index of the key in the fleet permissions profile
    pub key_index: u16,
}
