//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
use solana_pubkey::Pubkey;
/// Represents a points category & modifier as defined in the Points program

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq, Eq, Hash)]
pub struct SagePointsCategory {
    /// The points category
    pub category: Pubkey,
    /// The points category modifier
    pub modifier: Pubkey,
    /// The points category modifier bump
    pub modifier_bump: u8,
}
