//! This code was AUTOGENERATED using the Codama library.
use crate::MarketplaceDecoder;
use crate::PROGRAM_ID;

pub mod atlas_rate_account;
pub mod fee_reduction;
pub mod market_vars;
pub mod open_orders_counter;
pub mod order_account;
pub mod registered_currency;

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(tag = "type", content = "data"))]
pub enum MarketplaceAccount {
    AtlasRateAccount(Box<atlas_rate_account::AtlasRateAccount>),
    FeeReduction(Box<fee_reduction::FeeReduction>),
    MarketVars(Box<market_vars::MarketVars>),
    OpenOrdersCounter(Box<open_orders_counter::OpenOrdersCounter>),
    OrderAccount(Box<order_account::OrderAccount>),
    RegisteredCurrency(Box<registered_currency::RegisteredCurrency>),
}

impl<'a> carbon_core::account::AccountDecoder<'a> for MarketplaceDecoder {
    type AccountType = MarketplaceAccount;

    fn decode_account(
        &self,
        account: &'a solana_account::Account,
    ) -> Option<carbon_core::account::DecodedAccount<Self::AccountType>> {
        if account.owner != PROGRAM_ID {
            return None;
        }

        let data = account.data.as_slice();

        {
            if let Some(decoded) = atlas_rate_account::AtlasRateAccount::decode(data) {
                return Some(carbon_core::account::DecodedAccount {
                    lamports: account.lamports,
                    data: MarketplaceAccount::AtlasRateAccount(Box::new(decoded)),
                    owner: account.owner,
                    executable: account.executable,
                    rent_epoch: account.rent_epoch,
                });
            }
        }
        {
            if let Some(decoded) = fee_reduction::FeeReduction::decode(data) {
                return Some(carbon_core::account::DecodedAccount {
                    lamports: account.lamports,
                    data: MarketplaceAccount::FeeReduction(Box::new(decoded)),
                    owner: account.owner,
                    executable: account.executable,
                    rent_epoch: account.rent_epoch,
                });
            }
        }
        {
            if let Some(decoded) = market_vars::MarketVars::decode(data) {
                return Some(carbon_core::account::DecodedAccount {
                    lamports: account.lamports,
                    data: MarketplaceAccount::MarketVars(Box::new(decoded)),
                    owner: account.owner,
                    executable: account.executable,
                    rent_epoch: account.rent_epoch,
                });
            }
        }
        {
            if let Some(decoded) = open_orders_counter::OpenOrdersCounter::decode(data) {
                return Some(carbon_core::account::DecodedAccount {
                    lamports: account.lamports,
                    data: MarketplaceAccount::OpenOrdersCounter(Box::new(decoded)),
                    owner: account.owner,
                    executable: account.executable,
                    rent_epoch: account.rent_epoch,
                });
            }
        }
        {
            if let Some(decoded) = order_account::OrderAccount::decode(data) {
                return Some(carbon_core::account::DecodedAccount {
                    lamports: account.lamports,
                    data: MarketplaceAccount::OrderAccount(Box::new(decoded)),
                    owner: account.owner,
                    executable: account.executable,
                    rent_epoch: account.rent_epoch,
                });
            }
        }
        {
            if let Some(decoded) = registered_currency::RegisteredCurrency::decode(data) {
                return Some(carbon_core::account::DecodedAccount {
                    lamports: account.lamports,
                    data: MarketplaceAccount::RegisteredCurrency(Box::new(decoded)),
                    owner: account.owner,
                    executable: account.executable,
                    rent_epoch: account.rent_epoch,
                });
            }
        }

        None
    }
}
