//! This code was AUTOGENERATED using the Codama library.
use crate::types::OrderSide;
use carbon_core::CarbonDeserialize;
use carbon_core::borsh;
use carbon_core::deserialize::CarbonDeserialize;
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct OrderAccount {
    pub order_initializer_pubkey: Pubkey,
    pub currency_mint: Pubkey,
    pub asset_mint: Pubkey,
    pub initializer_currency_token_account: Pubkey,
    pub initializer_asset_token_account: Pubkey,
    pub order_side: OrderSide,
    pub price: u64,
    pub order_origination_qty: u64,
    pub order_remaining_qty: u64,
    pub created_at_timestamp: i64,
}

impl OrderAccount {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[79, 67, 112, 155, 214, 14, 32, 55] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}
