//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh::{self, BorshDeserialize};
use solana_pubkey::Pubkey;

use crate::types::RoleMembership;

/// A player's roles for a given profile
/// Remaining data contains an unordered list of [`RoleMembership`](RoleMembership) structs

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, PartialEq)]
pub struct ProfileRoleMembership {
    /// The data version of this account.
    pub version: u8,
    /// The Profile this belongs to
    pub profile: Pubkey,
    /// The member's profile pubkey
    pub member: Pubkey,
    /// PDA bump
    pub bump: u8,
    /// RemainingData: UnorderedList<RoleMembership, u32>
    pub memberships: Vec<RoleMembership>,
}

impl borsh::de::BorshDeserialize for ProfileRoleMembership
where
    u8: borsh::BorshDeserialize,
    Pubkey: borsh::BorshDeserialize,
{
    fn deserialize_reader<R: borsh::io::Read>(reader: &mut R) -> Result<Self, borsh::io::Error> {
        Ok(Self {
            version: borsh::BorshDeserialize::deserialize_reader(reader)?,
            profile: borsh::BorshDeserialize::deserialize_reader(reader)?,
            member: borsh::BorshDeserialize::deserialize_reader(reader)?,
            bump: borsh::BorshDeserialize::deserialize_reader(reader)?,
            memberships: Vec::new(), // Will be populated by CarbonDeserialize
        })
    }
}

impl carbon_core::deserialize::CarbonDeserialize for ProfileRoleMembership {
    const DISCRIMINATOR: &'static [u8] = &[45u8, 2u8, 86u8, 111u8, 110u8, 121u8, 5u8, 1u8];

    fn deserialize(data: &[u8]) -> Option<Self> {
        // ProfileRoleMembership has RemainingData = UnorderedList<RoleMembership, u32>
        // The u32 length prefix is stored after the fixed fields (66 bytes total)
        // Byte layout: version(1) + profile(32) + member(32) + bump(1) = 66 bytes

        let mut rest = data;

        let profile_role_membership: ProfileRoleMembership =
            match BorshDeserialize::deserialize(&mut rest) {
                Ok(res) => res,
                Err(_) => return None,
            };

        // Read u32 length prefix
        let list_length: u32 = match BorshDeserialize::deserialize(&mut rest) {
            Ok(count) => count,
            Err(_) => return None,
        };

        // Read each RoleMembership
        let mut memberships = Vec::with_capacity(list_length as usize);
        for _ in 0..list_length {
            let membership: RoleMembership = match BorshDeserialize::deserialize(&mut rest) {
                Ok(m) => m,
                Err(_) => return None,
            };
            memberships.push(membership);
        }

        let mut final_profile_role_membership = profile_role_membership;
        final_profile_role_membership.memberships = memberships;

        Some(final_profile_role_membership)
    }
}

impl ProfileRoleMembership {
    pub fn decode(data: &[u8]) -> Option<Self> {
        use carbon_core::deserialize::CarbonDeserialize;

        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != Self::DISCRIMINATOR {
            return None;
        }

        let data_slice = &data[8..];
        <ProfileRoleMembership as CarbonDeserialize>::deserialize(data_slice)
    }
}
