//! This code was AUTOGENERATED using the Codama library.
use crate::types::graphql::StarbaseCreateCraftingProcessInputGraphQL;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "CreateCraftingProcess")]
pub struct CreateCraftingProcessGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub input: StarbaseCreateCraftingProcessInputGraphQL,
}

impl TryFrom<crate::instructions::postgres::CreateCraftingProcessRow>
    for CreateCraftingProcessGraphQL
{
    type Error = carbon_core::error::Error;
    fn try_from(
        row: crate::instructions::postgres::CreateCraftingProcessRow,
    ) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            input: row.input.0.into(),
        })
    }
}
