//! This code was AUTOGENERATED using the Codama library.
use crate::types::graphql::StopMiningAsteroidInputGraphQL;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "StopMiningAsteroid")]
pub struct StopMiningAsteroidGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub input: StopMiningAsteroidInputGraphQL,
}

impl TryFrom<crate::instructions::postgres::StopMiningAsteroidRow> for StopMiningAsteroidGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(
        row: crate::instructions::postgres::StopMiningAsteroidRow,
    ) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            input: row.input.0.into(),
        })
    }
}
