//! This code was AUTOGENERATED using the Codama library.
use crate::types::graphql::UpdateShipInputGraphQL;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "UpdateShip")]
pub struct UpdateShipGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub input: UpdateShipInputGraphQL,
}

impl TryFrom<crate::instructions::postgres::UpdateShipRow> for UpdateShipGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::instructions::postgres::UpdateShipRow) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            input: row.input.0.into(),
        })
    }
}
