//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "CreateContract")]
pub struct CreateContractGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub rate: U64,
    pub duration_min: U64,
    pub duration_max: U64,
    pub payments_feq: String,
    pub owner_key_index: i32,
}

impl TryFrom<crate::instructions::postgres::CreateContractRow> for CreateContractGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(
        row: crate::instructions::postgres::CreateContractRow,
    ) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            rate: carbon_core::graphql::primitives::U64(*row.rate),
            duration_min: carbon_core::graphql::primitives::U64(*row.duration_min),
            duration_max: carbon_core::graphql::primitives::U64(*row.duration_max),
            payments_feq: row.payments_feq,
            owner_key_index: (*row.owner_key_index) as i32,
        })
    }
}
