//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "InitCargoTypeInput")]
pub struct InitCargoTypeInputGraphQL {
    pub key_index: i32,
    pub values: Vec<U64>,
}

impl From<crate::types::InitCargoTypeInput> for InitCargoTypeInputGraphQL {
    fn from(original: crate::types::InitCargoTypeInput) -> Self {
        Self {
            key_index: original.key_index as i32,
            values: original
                .values
                .into_iter()
                .map(|item| carbon_core::graphql::primitives::U64(item))
                .collect(),
        }
    }
}
