//! This code was AUTOGENERATED using the Codama library.
use solana_pubkey::Pubkey;
pub struct PlayerProfileDecoder;
pub const PROGRAM_ID: Pubkey =
    solana_pubkey::Pubkey::from_str_const("pprofELXjL5Kck7Jn5hCpwAL82DpTkSYBENzahVtbc9");

pub mod accounts;
pub mod instructions;
pub mod types;
