//! This code was AUTOGENERATED using the Codama library.
use crate::PROGRAM_ID;
use crate::ScoreDecoder;

pub mod process_close_accounts;
pub mod process_deregister_ship;
pub mod process_harvest;
pub mod process_initial_deposit;
pub mod process_initialize;
pub mod process_partial_deposit;
pub mod process_rearm;
pub mod process_refeed;
pub mod process_refuel;
pub mod process_register_ship;
pub mod process_repair;
pub mod process_settle;
pub mod process_update_reward_rate;
pub mod process_withdraw_arms;
pub mod process_withdraw_food;
pub mod process_withdraw_fuel;
pub mod process_withdraw_ships;

pub use self::process_close_accounts::*;
pub use self::process_deregister_ship::*;
pub use self::process_harvest::*;
pub use self::process_initial_deposit::*;
pub use self::process_initialize::*;
pub use self::process_partial_deposit::*;
pub use self::process_rearm::*;
pub use self::process_refeed::*;
pub use self::process_refuel::*;
pub use self::process_register_ship::*;
pub use self::process_repair::*;
pub use self::process_settle::*;
pub use self::process_update_reward_rate::*;
pub use self::process_withdraw_arms::*;
pub use self::process_withdraw_food::*;
pub use self::process_withdraw_fuel::*;
pub use self::process_withdraw_ships::*;

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[cfg_attr(
    feature = "serde",
    derive(carbon_core::InstructionType, serde::Serialize, serde::Deserialize)
)]
#[cfg_attr(feature = "serde", serde(tag = "type", content = "data"))]
pub enum ScoreInstruction {
    ProcessCloseAccounts(ProcessCloseAccounts),
    ProcessDeregisterShip(ProcessDeregisterShip),
    ProcessHarvest(ProcessHarvest),
    ProcessInitialDeposit(ProcessInitialDeposit),
    ProcessInitialize(ProcessInitialize),
    ProcessPartialDeposit(ProcessPartialDeposit),
    ProcessRearm(ProcessRearm),
    ProcessRefeed(ProcessRefeed),
    ProcessRefuel(ProcessRefuel),
    ProcessRegisterShip(ProcessRegisterShip),
    ProcessRepair(ProcessRepair),
    ProcessSettle(ProcessSettle),
    ProcessUpdateRewardRate(ProcessUpdateRewardRate),
    ProcessWithdrawArms(ProcessWithdrawArms),
    ProcessWithdrawFood(ProcessWithdrawFood),
    ProcessWithdrawFuel(ProcessWithdrawFuel),
    ProcessWithdrawShips(ProcessWithdrawShips),
}

impl carbon_core::instruction::InstructionDecoder<'_> for ScoreDecoder {
    type InstructionType = ScoreInstruction;

    fn decode_instruction(
        &self,
        instruction: &solana_instruction::Instruction,
    ) -> Option<carbon_core::instruction::DecodedInstruction<Self::InstructionType>> {
        if !instruction.program_id.eq(&PROGRAM_ID) {
            return None;
        }

        let data = instruction.data.as_slice();

        {
            if let Some(decoded) = process_close_accounts::ProcessCloseAccounts::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: ScoreInstruction::ProcessCloseAccounts(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = process_deregister_ship::ProcessDeregisterShip::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: ScoreInstruction::ProcessDeregisterShip(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = process_harvest::ProcessHarvest::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: ScoreInstruction::ProcessHarvest(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = process_initial_deposit::ProcessInitialDeposit::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: ScoreInstruction::ProcessInitialDeposit(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = process_initialize::ProcessInitialize::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: ScoreInstruction::ProcessInitialize(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = process_partial_deposit::ProcessPartialDeposit::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: ScoreInstruction::ProcessPartialDeposit(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = process_rearm::ProcessRearm::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: ScoreInstruction::ProcessRearm(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = process_refeed::ProcessRefeed::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: ScoreInstruction::ProcessRefeed(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = process_refuel::ProcessRefuel::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: ScoreInstruction::ProcessRefuel(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = process_register_ship::ProcessRegisterShip::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: ScoreInstruction::ProcessRegisterShip(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = process_repair::ProcessRepair::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: ScoreInstruction::ProcessRepair(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = process_settle::ProcessSettle::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: ScoreInstruction::ProcessSettle(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = process_update_reward_rate::ProcessUpdateRewardRate::decode(data)
            {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: ScoreInstruction::ProcessUpdateRewardRate(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = process_withdraw_arms::ProcessWithdrawArms::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: ScoreInstruction::ProcessWithdrawArms(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = process_withdraw_food::ProcessWithdrawFood::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: ScoreInstruction::ProcessWithdrawFood(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = process_withdraw_fuel::ProcessWithdrawFuel::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: ScoreInstruction::ProcessWithdrawFuel(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = process_withdraw_ships::ProcessWithdrawShips::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: ScoreInstruction::ProcessWithdrawShips(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }

        None
    }
}
