//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq, Eq, Hash)]
pub struct ProcessRefuel {
    pub staking_bump: u8,
    pub scorevars_bump: u8,
    pub scorevars_ship_bump: u8,
    pub escrow_auth_bump: u8,
    pub escrow_bump: u8,
    pub fuel_quantity: u64,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ProcessRefuelInstructionAccounts {
    pub token_owner_account: solana_pubkey::Pubkey,
    pub player_account: solana_pubkey::Pubkey,
    pub ship_staking_account: solana_pubkey::Pubkey,
    pub score_vars_account: solana_pubkey::Pubkey,
    pub score_vars_ship_account: solana_pubkey::Pubkey,
    pub escrow_authority: solana_pubkey::Pubkey,
    pub system_program: solana_pubkey::Pubkey,
    pub token_program: solana_pubkey::Pubkey,
    pub clock: solana_pubkey::Pubkey,
    pub rent: solana_pubkey::Pubkey,
    pub ship_mint: solana_pubkey::Pubkey,
    pub fuel_mint: solana_pubkey::Pubkey,
    pub fuel_token_account_source: solana_pubkey::Pubkey,
    pub fuel_token_account_escrow: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl ProcessRefuel {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[210, 42, 60, 152, 93, 215, 170, 115] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for ProcessRefuel {
    type ArrangedAccounts = ProcessRefuelInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let token_owner_account = next_account(&mut iter)?;
        let player_account = next_account(&mut iter)?;
        let ship_staking_account = next_account(&mut iter)?;
        let score_vars_account = next_account(&mut iter)?;
        let score_vars_ship_account = next_account(&mut iter)?;
        let escrow_authority = next_account(&mut iter)?;
        let system_program = next_account(&mut iter)?;
        let token_program = next_account(&mut iter)?;
        let clock = next_account(&mut iter)?;
        let rent = next_account(&mut iter)?;
        let ship_mint = next_account(&mut iter)?;
        let fuel_mint = next_account(&mut iter)?;
        let fuel_token_account_source = next_account(&mut iter)?;
        let fuel_token_account_escrow = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(ProcessRefuelInstructionAccounts {
            token_owner_account,
            player_account,
            ship_staking_account,
            score_vars_account,
            score_vars_ship_account,
            escrow_authority,
            system_program,
            token_program,
            clock,
            rent,
            ship_mint,
            fuel_mint,
            fuel_token_account_source,
            fuel_token_account_escrow,
            remaining: remaining.to_vec(),
        })
    }
}
