//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq, Eq, Hash)]
pub struct ProcessWithdrawFood {
    pub staking_bump: u8,
    pub scorevars_bump: u8,
    pub scorevars_ship_bump: u8,
    pub escrow_auth_bump: u8,
    pub escrow_bump: u8,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ProcessWithdrawFoodInstructionAccounts {
    pub player_account: solana_pubkey::Pubkey,
    pub ship_staking_account: solana_pubkey::Pubkey,
    pub score_vars_account: solana_pubkey::Pubkey,
    pub score_vars_ship_account: solana_pubkey::Pubkey,
    pub food_token_account_escrow: solana_pubkey::Pubkey,
    pub food_token_account_return: solana_pubkey::Pubkey,
    pub food_mint: solana_pubkey::Pubkey,
    pub escrow_authority: solana_pubkey::Pubkey,
    pub token_program: solana_pubkey::Pubkey,
    pub clock: solana_pubkey::Pubkey,
    pub ship_mint: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl ProcessWithdrawFood {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[158, 156, 93, 72, 55, 33, 152, 149] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for ProcessWithdrawFood {
    type ArrangedAccounts = ProcessWithdrawFoodInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let player_account = next_account(&mut iter)?;
        let ship_staking_account = next_account(&mut iter)?;
        let score_vars_account = next_account(&mut iter)?;
        let score_vars_ship_account = next_account(&mut iter)?;
        let food_token_account_escrow = next_account(&mut iter)?;
        let food_token_account_return = next_account(&mut iter)?;
        let food_mint = next_account(&mut iter)?;
        let escrow_authority = next_account(&mut iter)?;
        let token_program = next_account(&mut iter)?;
        let clock = next_account(&mut iter)?;
        let ship_mint = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(ProcessWithdrawFoodInstructionAccounts {
            player_account,
            ship_staking_account,
            score_vars_account,
            score_vars_ship_account,
            food_token_account_escrow,
            food_token_account_return,
            food_mint,
            escrow_authority,
            token_program,
            clock,
            ship_mint,
            remaining: remaining.to_vec(),
        })
    }
}
