//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
/// Input for `RemoveRedemptionEpoch`

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq, Eq, Hash)]
pub struct RemoveRedemptionEpochInput {
    /// The index of epoch in the `RedemptionConfig` epoch array
    pub epoch_index: u16,
    /// the index of the key in the player profile
    pub key_index: u16,
}
