//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
/// Input for `StartRedemption`

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq, Eq, Hash)]
pub struct StartRedemptionInput {
    /// The number of points to submit
    pub points: u64,
    /// the index of the epoch in the `RedemptionConfig` account
    pub epoch_index: u16,
    /// the index of the key that can spend points in the player profile
    pub key_index: u16,
}
