//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
/// Input for `UpdateRedemptionEpoch`

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq, Eq, Hash)]
pub struct UpdateRedemptionEpochInput {
    /// The total tokens that can redeemed for this epoch
    pub total_tokens: u64,
    /// The index of epoch in the `RedemptionConfig` epoch array
    pub epoch_index: u16,
    /// the index of the key in the player profile
    pub key_index: u16,
}
