//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U8;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "RegisterCraftableItemInput")]
pub struct RegisterCraftableItemInputGraphQL {
    pub namespace: Vec<U8>,
    pub key_index: i32,
}

impl From<crate::types::RegisterCraftableItemInput> for RegisterCraftableItemInputGraphQL {
    fn from(original: crate::types::RegisterCraftableItemInput) -> Self {
        Self {
            namespace: original
                .namespace
                .into_iter()
                .map(|item| carbon_core::graphql::primitives::U8(item))
                .collect(),
            key_index: original.key_index as i32,
        }
    }
}
