//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::I64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "StopCraftingProcessInput")]
pub struct StopCraftingProcessInputGraphQL {
    pub local_time: Option<I64>,
}

impl From<crate::types::StopCraftingProcessInput> for StopCraftingProcessInputGraphQL {
    fn from(original: crate::types::StopCraftingProcessInput) -> Self {
        Self {
            local_time: original
                .local_time
                .map(|v| carbon_core::graphql::primitives::I64(v)),
        }
    }
}
