//! This code was AUTOGENERATED using the Codama library.
use crate::types::ClockData;
use crate::types::ExecContext;
use crate::types::SerializableInstruction;
use crate::types::Trigger;
use carbon_core::account::AccountMetadata;
use carbon_core::postgres::metadata::AccountRowMetadata;
use carbon_core::postgres::primitives::Pubkey;
use carbon_core::postgres::primitives::U8;
use carbon_core::postgres::primitives::U64;

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct ThreadRow {
    #[sqlx(flatten)]
    pub account_metadata: AccountRowMetadata,
    pub authority: Pubkey,
    pub bump: U8,
    pub created_at: sqlx::types::Json<ClockData>,
    pub exec_context: Option<sqlx::types::Json<ExecContext>>,
    pub fee: U64,
    pub id: Vec<u8>,
    pub instructions: sqlx::types::Json<Vec<SerializableInstruction>>,
    pub name: String,
    pub next_instruction: Option<sqlx::types::Json<SerializableInstruction>>,
    pub paused: bool,
    pub rate_limit: U64,
    pub trigger: sqlx::types::Json<Trigger>,
}

impl ThreadRow {
    pub fn from_parts(source: crate::accounts::thread::Thread, metadata: AccountMetadata) -> Self {
        Self {
            account_metadata: metadata.into(),
            authority: source.authority.into(),
            bump: source.bump.into(),
            created_at: sqlx::types::Json(source.created_at.into()),
            exec_context: source
                .exec_context
                .map(|value| sqlx::types::Json(value.into())),
            fee: source.fee.into(),
            id: source.id.into(),
            instructions: sqlx::types::Json(
                source
                    .instructions
                    .into_iter()
                    .map(|element| element.into())
                    .collect(),
            ),
            name: source.name.into(),
            next_instruction: source
                .next_instruction
                .map(|value| sqlx::types::Json(value.into())),
            paused: source.paused.into(),
            rate_limit: source.rate_limit.into(),
            trigger: sqlx::types::Json(source.trigger.into()),
        }
    }
}

impl TryFrom<ThreadRow> for crate::accounts::thread::Thread {
    type Error = carbon_core::error::Error;
    fn try_from(source: ThreadRow) -> Result<Self, Self::Error> {
        Ok(Self {
            authority: *source.authority,
            bump: source.bump.try_into().map_err(|_| {
                carbon_core::error::Error::Custom(
                    "Failed to convert value from postgres primitive".to_string(),
                )
            })?,
            created_at: source.created_at.0,
            exec_context: source.exec_context.map(|value| value.0),
            fee: *source.fee,
            id: source.id.into(),
            instructions: source.instructions.0,
            name: source.name.into(),
            next_instruction: source.next_instruction.map(|value| value.0),
            paused: source.paused.into(),
            rate_limit: *source.rate_limit,
            trigger: source.trigger.0,
        })
    }
}

impl carbon_core::postgres::operations::Table for crate::accounts::thread::Thread {
    fn table() -> &'static str {
        "thread_account"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__pubkey",
            "__slot",
            "authority",
            "bump",
            "created_at",
            "exec_context",
            "fee",
            "id",
            "instructions",
            "name",
            "next_instruction",
            "paused",
            "rate_limit",
            "trigger",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for ThreadRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"
            INSERT INTO thread_account (
                "authority",
                "bump",
                "created_at",
                "exec_context",
                "fee",
                "id",
                "instructions",
                "name",
                "next_instruction",
                "paused",
                "rate_limit",
                "trigger",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
            )"#,
        )
        .bind(self.authority.clone())
        .bind(self.bump.clone())
        .bind(self.created_at.clone())
        .bind(self.exec_context.clone())
        .bind(self.fee.clone())
        .bind(self.id.clone())
        .bind(self.instructions.clone())
        .bind(self.name.clone())
        .bind(self.next_instruction.clone())
        .bind(self.paused.clone())
        .bind(self.rate_limit.clone())
        .bind(self.trigger.clone())
        .bind(self.account_metadata.pubkey.clone())
        .bind(self.account_metadata.slot.clone())
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for ThreadRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"INSERT INTO thread_account (
                "authority",
                "bump",
                "created_at",
                "exec_context",
                "fee",
                "id",
                "instructions",
                "name",
                "next_instruction",
                "paused",
                "rate_limit",
                "trigger",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
            ) ON CONFLICT (
                __pubkey
            ) DO UPDATE SET
                "authority" = EXCLUDED."authority",
                "bump" = EXCLUDED."bump",
                "created_at" = EXCLUDED."created_at",
                "exec_context" = EXCLUDED."exec_context",
                "fee" = EXCLUDED."fee",
                "id" = EXCLUDED."id",
                "instructions" = EXCLUDED."instructions",
                "name" = EXCLUDED."name",
                "next_instruction" = EXCLUDED."next_instruction",
                "paused" = EXCLUDED."paused",
                "rate_limit" = EXCLUDED."rate_limit",
                "trigger" = EXCLUDED."trigger",
                __slot = EXCLUDED.__slot
            "#,
        )
        .bind(self.authority.clone())
        .bind(self.bump.clone())
        .bind(self.created_at.clone())
        .bind(self.exec_context.clone())
        .bind(self.fee.clone())
        .bind(self.id.clone())
        .bind(self.instructions.clone())
        .bind(self.name.clone())
        .bind(self.next_instruction.clone())
        .bind(self.paused.clone())
        .bind(self.rate_limit.clone())
        .bind(self.trigger.clone())
        .bind(self.account_metadata.pubkey)
        .bind(self.account_metadata.slot.clone())
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for ThreadRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"DELETE FROM thread_account WHERE
                __pubkey = $1
            "#,
        )
        .bind(key)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for ThreadRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn lookup(
        key: Self::Key,
        pool: &sqlx::PgPool,
    ) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(
            r#"SELECT * FROM thread_account WHERE
                __pubkey = $1
            "#,
        )
        .bind(key)
        .fetch_optional(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct ThreadMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for ThreadMigrationOperation {
    async fn up(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(
            r#"CREATE TABLE IF NOT EXISTS thread_account (
                -- Account data
                "authority" BYTEA NOT NULL,
                "bump" INT2 NOT NULL,
                "created_at" JSONB NOT NULL,
                "exec_context" JSONB,
                "fee" NUMERIC(20) NOT NULL,
                "id" BYTEA NOT NULL,
                "instructions" JSONB NOT NULL,
                "name" TEXT NOT NULL,
                "next_instruction" JSONB,
                "paused" BOOLEAN NOT NULL,
                "rate_limit" NUMERIC(20) NOT NULL,
                "trigger" JSONB NOT NULL,
                -- Account metadata
                __pubkey BYTEA NOT NULL,
                __slot NUMERIC(20),
                PRIMARY KEY (__pubkey)
            )"#,
        )
        .execute(connection)
        .await?;
        Ok(())
    }

    async fn down(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS thread_account"#)
            .execute(connection)
            .await?;
        Ok(())
    }
}
