//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
/// Struct for data input to `AttackStarbase`

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq, Eq, Hash)]
pub struct AttackStarbaseInput {
    /// the index of the key in the player profile
    pub key_index: u16,
}
