//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
/// Struct for data input to Dev Add Crew

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct DevAddCrewInput {
    /// The index of the key in the permissions profile
    pub key_index: u16,
    /// The number of crew to add or remove
    pub crew_count: i32,
}
