//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
/// Struct for data input to update miscellaneous settings

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq, Eq, Hash)]
pub struct MiscVariablesInput {
    /// Percentage by which the "warp lane" movement type reduces warp fuel cost
    pub warp_lane_fuel_cost_reduction: Option<i16>,
    /// Percentage by which to reduce the asteroid mining rate if a starbase ammo upkeep coffer is empty
    pub upkeep_mining_emissions_penalty: Option<i16>,
    /// Respawn fee, charged in ATLAS
    pub respawn_fee: Option<u64>,
}
