//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
/// Struct for data input to Register a Resource

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct RegisterResourceInput {
    /// `Resource` location type
    pub location_type: u8,
    /// `Resource` `system_richness`
    pub system_richness: u16,
    /// the index of the key in the fleet permissions profile
    pub key_index: u16,
}
