//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
/// Struct for data input to Register SurveyDataUnitTracker

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq, Eq, Hash)]
pub struct RegisterSurveyDataUnitTrackerInput {
    /// The valid coordinates range
    /// e.g. a value of [-50, 50] means that coordinates from [-50, -50] to [50, 50] are valid for SDU scanning
    pub coordinates_range: [i64; 2],
    /// The locations of the central space stations (CSS) of the three factions
    pub css_coordinates: [[i64; 2]; 3],
    /// The co-ordinates of the "origin"; used in calculating SDU probability
    pub origin_coordinates: [i64; 2],
    /// The max distance from the nearest CSS; used in calculating SDU probability
    pub css_max_distance: u32,
    /// The max distance from the `origin_coordinates`; used in calculating SDU probability
    pub origin_max_distance: u32,
    /// The distance weighting; used in calculating SDU probability
    pub distance_weighting: u32,
    /// The maximum time before SDU probability at a location changes
    pub t_max: i64,
    /// Multiplier in the X dimension; used in noise function
    pub x_mul: u32,
    /// Multiplier in the Y dimension; used in noise function
    pub y_mul: u32,
    /// Multiplier in the Z dimension; used in noise function
    pub z_mul: u32,
    /// The maximum number of SDUs that can be found per scan per sector
    pub sdu_max_per_sector: u32,
    /// The amount of time in seconds that it takes for a sector scan chance to fully regenerate
    pub scan_chance_regen_period: i16,
    /// the index of the key in the sector permissions profile
    pub key_index: u16,
}
