//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
/// Unpacked version of [`RegisterStarbaseInput`]

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq, Eq, Hash)]
pub struct RegisterStarbaseInputUnpacked {
    /// `Starbase` name
    #[cfg_attr(feature = "serde", serde(with = "serde_big_array::BigArray"))]
    pub name: [u8; 64],
    /// `Starbase` coordinates
    pub sub_coordinates: [i64; 2],
    /// The index representing the level of the `Starbase` in the game variables.
    pub starbase_level_index: u8,
    /// The `Starbase` faction
    pub faction: u8,
    /// the index of the key in the fleet permissions profile
    pub key_index: u16,
}
