//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
/// Represents the orbital position of a `Planet` in the `Sector`

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub enum SectorRing {
    Inner,
    Mid,
    Outer,
}
