//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
/// Represents different types of Ships

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub enum SizeClass {
    XxSmall,
    XSmall,
    Small,
    Medium,
    Large,
    Capital,
    Commander,
    Titan,
}
