//! This code was AUTOGENERATED using the Codama library.
use crate::types::RiskZonesDataUnpacked;
use carbon_core::borsh;
/// Struct for data input to Update instruction

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq, Eq, Hash)]
pub struct UpdateGameInput {
    /// Cargo settings
    pub cargo: u8,
    /// Crafting settings
    pub crafting: u8,
    /// Mints
    pub mints: u8,
    /// Vaults
    pub vaults: u8,
    /// Points settings
    pub points: u8,
    /// Data for risk zones
    pub risk_zones: Option<RiskZonesDataUnpacked>,
    /// the index of the key in the sector permissions profile
    pub key_index: u16,
}
