//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
/// Struct for data input to Register a Resource

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct UpdateMineItemInput {
    /// The name of the `MineItem`
    pub name: Option<Vec<u8>>,
    /// How hard it is to mine this item
    pub resource_hardness: Option<u16>,
    /// the index of the key in the fleet permissions profile
    pub key_index: u16,
}
