//! This code was AUTOGENERATED using the Codama library.
use carbon_core::account::AccountMetadata;
use carbon_core::postgres::metadata::AccountRowMetadata;
use carbon_core::postgres::primitives::Pubkey;
use carbon_core::postgres::primitives::U8;
use carbon_core::postgres::primitives::U16;
use carbon_core::postgres::primitives::U64;

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct StakingAccountRow {
    #[sqlx(flatten)]
    pub account_metadata: AccountRowMetadata,
    pub owner: Pubkey,
    pub registered_stake: Pubkey,
    pub stake_mint: Pubkey,
    pub total_stake: U64,
    pub active_stake: U64,
    pub pending_rewards: U64,
    pub paid_rewards: U64,
    pub current_period: U16,
    pub staked_at_ts: i64,
    pub last_pending_reward_calc_ts: i64,
    pub last_harvest_ts: i64,
    pub unstaked_ts: i64,
    pub bump: U8,
}

impl StakingAccountRow {
    pub fn from_parts(
        source: crate::accounts::staking_account::StakingAccount,
        metadata: AccountMetadata,
    ) -> Self {
        Self {
            account_metadata: metadata.into(),
            owner: source.owner.into(),
            registered_stake: source.registered_stake.into(),
            stake_mint: source.stake_mint.into(),
            total_stake: source.total_stake.into(),
            active_stake: source.active_stake.into(),
            pending_rewards: source.pending_rewards.into(),
            paid_rewards: source.paid_rewards.into(),
            current_period: source.current_period.into(),
            staked_at_ts: source.staked_at_ts.into(),
            last_pending_reward_calc_ts: source.last_pending_reward_calc_ts.into(),
            last_harvest_ts: source.last_harvest_ts.into(),
            unstaked_ts: source.unstaked_ts.into(),
            bump: source.bump.into(),
        }
    }
}

impl TryFrom<StakingAccountRow> for crate::accounts::staking_account::StakingAccount {
    type Error = carbon_core::error::Error;
    fn try_from(source: StakingAccountRow) -> Result<Self, Self::Error> {
        Ok(Self {
            owner: *source.owner,
            registered_stake: *source.registered_stake,
            stake_mint: *source.stake_mint,
            total_stake: *source.total_stake,
            active_stake: *source.active_stake,
            pending_rewards: *source.pending_rewards,
            paid_rewards: *source.paid_rewards,
            current_period: source.current_period.try_into().map_err(|_| {
                carbon_core::error::Error::Custom(
                    "Failed to convert value from postgres primitive".to_string(),
                )
            })?,
            staked_at_ts: source.staked_at_ts.into(),
            last_pending_reward_calc_ts: source.last_pending_reward_calc_ts.into(),
            last_harvest_ts: source.last_harvest_ts.into(),
            unstaked_ts: source.unstaked_ts.into(),
            bump: source.bump.try_into().map_err(|_| {
                carbon_core::error::Error::Custom(
                    "Failed to convert value from postgres primitive".to_string(),
                )
            })?,
        })
    }
}

impl carbon_core::postgres::operations::Table for crate::accounts::staking_account::StakingAccount {
    fn table() -> &'static str {
        "staking_account_account"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__pubkey",
            "__slot",
            "owner",
            "registered_stake",
            "stake_mint",
            "total_stake",
            "active_stake",
            "pending_rewards",
            "paid_rewards",
            "current_period",
            "staked_at_ts",
            "last_pending_reward_calc_ts",
            "last_harvest_ts",
            "unstaked_ts",
            "bump",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for StakingAccountRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"
            INSERT INTO staking_account_account (
                "owner",
                "registered_stake",
                "stake_mint",
                "total_stake",
                "active_stake",
                "pending_rewards",
                "paid_rewards",
                "current_period",
                "staked_at_ts",
                "last_pending_reward_calc_ts",
                "last_harvest_ts",
                "unstaked_ts",
                "bump",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
            )"#,
        )
        .bind(self.owner.clone())
        .bind(self.registered_stake.clone())
        .bind(self.stake_mint.clone())
        .bind(self.total_stake.clone())
        .bind(self.active_stake.clone())
        .bind(self.pending_rewards.clone())
        .bind(self.paid_rewards.clone())
        .bind(self.current_period.clone())
        .bind(self.staked_at_ts.clone())
        .bind(self.last_pending_reward_calc_ts.clone())
        .bind(self.last_harvest_ts.clone())
        .bind(self.unstaked_ts.clone())
        .bind(self.bump.clone())
        .bind(self.account_metadata.pubkey.clone())
        .bind(self.account_metadata.slot.clone())
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for StakingAccountRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"INSERT INTO staking_account_account (
                "owner",
                "registered_stake",
                "stake_mint",
                "total_stake",
                "active_stake",
                "pending_rewards",
                "paid_rewards",
                "current_period",
                "staked_at_ts",
                "last_pending_reward_calc_ts",
                "last_harvest_ts",
                "unstaked_ts",
                "bump",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
            ) ON CONFLICT (
                __pubkey
            ) DO UPDATE SET
                "owner" = EXCLUDED."owner",
                "registered_stake" = EXCLUDED."registered_stake",
                "stake_mint" = EXCLUDED."stake_mint",
                "total_stake" = EXCLUDED."total_stake",
                "active_stake" = EXCLUDED."active_stake",
                "pending_rewards" = EXCLUDED."pending_rewards",
                "paid_rewards" = EXCLUDED."paid_rewards",
                "current_period" = EXCLUDED."current_period",
                "staked_at_ts" = EXCLUDED."staked_at_ts",
                "last_pending_reward_calc_ts" = EXCLUDED."last_pending_reward_calc_ts",
                "last_harvest_ts" = EXCLUDED."last_harvest_ts",
                "unstaked_ts" = EXCLUDED."unstaked_ts",
                "bump" = EXCLUDED."bump",
                __slot = EXCLUDED.__slot
            "#,
        )
        .bind(self.owner.clone())
        .bind(self.registered_stake.clone())
        .bind(self.stake_mint.clone())
        .bind(self.total_stake.clone())
        .bind(self.active_stake.clone())
        .bind(self.pending_rewards.clone())
        .bind(self.paid_rewards.clone())
        .bind(self.current_period.clone())
        .bind(self.staked_at_ts.clone())
        .bind(self.last_pending_reward_calc_ts.clone())
        .bind(self.last_harvest_ts.clone())
        .bind(self.unstaked_ts.clone())
        .bind(self.bump.clone())
        .bind(self.account_metadata.pubkey)
        .bind(self.account_metadata.slot.clone())
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for StakingAccountRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(
            r#"DELETE FROM staking_account_account WHERE
                __pubkey = $1
            "#,
        )
        .bind(key)
        .execute(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for StakingAccountRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn lookup(
        key: Self::Key,
        pool: &sqlx::PgPool,
    ) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(
            r#"SELECT * FROM staking_account_account WHERE
                __pubkey = $1
            "#,
        )
        .bind(key)
        .fetch_optional(pool)
        .await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct StakingAccountMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for StakingAccountMigrationOperation {
    async fn up(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(
            r#"CREATE TABLE IF NOT EXISTS staking_account_account (
                -- Account data
                "owner" BYTEA NOT NULL,
                "registered_stake" BYTEA NOT NULL,
                "stake_mint" BYTEA NOT NULL,
                "total_stake" NUMERIC(20) NOT NULL,
                "active_stake" NUMERIC(20) NOT NULL,
                "pending_rewards" NUMERIC(20) NOT NULL,
                "paid_rewards" NUMERIC(20) NOT NULL,
                "current_period" INT4 NOT NULL,
                "staked_at_ts" INT8 NOT NULL,
                "last_pending_reward_calc_ts" INT8 NOT NULL,
                "last_harvest_ts" INT8 NOT NULL,
                "unstaked_ts" INT8 NOT NULL,
                "bump" INT2 NOT NULL,
                -- Account metadata
                __pubkey BYTEA NOT NULL,
                __slot NUMERIC(20),
                PRIMARY KEY (__pubkey)
            )"#,
        )
        .execute(connection)
        .await?;
        Ok(())
    }

    async fn down(
        &self,
        connection: &mut sqlx::PgConnection,
    ) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS staking_account_account"#)
            .execute(connection)
            .await?;
        Ok(())
    }
}
