//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;

/// Creates a new [LockerWhitelistEntry] to whitelist program from CPI.

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq, Eq, Hash)]
pub struct ApproveProgramLockPrivilege {
    pub bump: u8,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ApproveProgramLockPrivilegeInstructionAccounts {
    pub locker: solana_pubkey::Pubkey,
    pub whitelist_entry: solana_pubkey::Pubkey,
    pub governor: solana_pubkey::Pubkey,
    pub smart_wallet: solana_pubkey::Pubkey,
    pub executable_id: solana_pubkey::Pubkey,
    pub whitelisted_owner: solana_pubkey::Pubkey,
    pub payer: solana_pubkey::Pubkey,
    pub system_program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl ApproveProgramLockPrivilege {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[75, 202, 1, 4, 122, 110, 102, 148] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for ApproveProgramLockPrivilege {
    type ArrangedAccounts = ApproveProgramLockPrivilegeInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let locker = next_account(&mut iter)?;
        let whitelist_entry = next_account(&mut iter)?;
        let governor = next_account(&mut iter)?;
        let smart_wallet = next_account(&mut iter)?;
        let executable_id = next_account(&mut iter)?;
        let whitelisted_owner = next_account(&mut iter)?;
        let payer = next_account(&mut iter)?;
        let system_program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(ApproveProgramLockPrivilegeInstructionAccounts {
            locker,
            whitelist_entry,
            governor,
            smart_wallet,
            executable_id,
            whitelisted_owner,
            payer,
            system_program,
            remaining: remaining.to_vec(),
        })
    }
}
