//! This code was AUTOGENERATED using the Codama library.
use crate::types::UpdateDefinitionInput;
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;

/// Updates a [`CargoStatsDefinition`](state::CargoStatsDefinition) account.
/// Will advance the `seq_id` unless `rollback` is set to true.

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct UpdateDefinition {
    pub input: UpdateDefinitionInput,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct UpdateDefinitionInstructionAccounts {
    pub key: solana_pubkey::Pubkey,
    pub profile: solana_pubkey::Pubkey,
    pub stats_definition: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl UpdateDefinition {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[153, 186, 206, 218, 233, 87, 179, 150] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for UpdateDefinition {
    type ArrangedAccounts = UpdateDefinitionInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let key = next_account(&mut iter)?;
        let profile = next_account(&mut iter)?;
        let stats_definition = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(UpdateDefinitionInstructionAccounts {
            key,
            profile,
            stats_definition,
            remaining: remaining.to_vec(),
        })
    }
}
