//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
/// Struct for data input to claim a non-consumable ingredient

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct ClaimNonConsumableIngredientInput {
    /// the index of the recipe ingredient
    pub ingredient_index: u16,
    /// the current time as supplied by the location; required if `use_local_time` is set on the `CraftingProcess`
    pub local_time: Option<i64>,
}
