//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
use solana_pubkey::Pubkey;
/// A copy of the [`RecipeInputsOutputs`] struct --> to be used as inputs into the program, avoiding using Borsch Serialization with Zero Copy serialization

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct RecipeIngredients {
    /// Amount of Input/Output required/produced.
    pub amount: u64,
    /// Mint pubkey of the Input/Output.
    pub mint: Pubkey,
    /// the index of the key in the crafting permissions profile
    pub key_index: u16,
}
