//! This code was AUTOGENERATED using the Codama library.
use crate::types::ClaimTokensInput;
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq, Eq, Hash)]
pub struct ClaimTokens {
    pub input: ClaimTokensInput,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ClaimTokensInstructionAccounts {
    pub key: solana_pubkey::Pubkey,
    pub funds_to: solana_pubkey::Pubkey,
    pub user_profile: solana_pubkey::Pubkey,
    pub user_redemption_account: solana_pubkey::Pubkey,
    pub config: solana_pubkey::Pubkey,
    pub config_signer: solana_pubkey::Pubkey,
    pub bank: solana_pubkey::Pubkey,
    pub tokens_to: solana_pubkey::Pubkey,
    pub token_program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl ClaimTokens {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[108, 216, 210, 231, 0, 212, 42, 64] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for ClaimTokens {
    type ArrangedAccounts = ClaimTokensInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let key = next_account(&mut iter)?;
        let funds_to = next_account(&mut iter)?;
        let user_profile = next_account(&mut iter)?;
        let user_redemption_account = next_account(&mut iter)?;
        let config = next_account(&mut iter)?;
        let config_signer = next_account(&mut iter)?;
        let bank = next_account(&mut iter)?;
        let tokens_to = next_account(&mut iter)?;
        let token_program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(ClaimTokensInstructionAccounts {
            key,
            funds_to,
            user_profile,
            user_redemption_account,
            config,
            config_signer,
            bank,
            tokens_to,
            token_program,
            remaining: remaining.to_vec(),
        })
    }
}
