//! This code was AUTOGENERATED using the Codama library.
use crate::types::UpdateRedemptionEpochInput;
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq, Eq, Hash)]
pub struct UpdateRedemptionEpoch {
    pub input: UpdateRedemptionEpochInput,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct UpdateRedemptionEpochInstructionAccounts {
    pub key: solana_pubkey::Pubkey,
    pub profile: solana_pubkey::Pubkey,
    pub config: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl UpdateRedemptionEpoch {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[164, 224, 163, 159, 60, 207, 84, 190] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for UpdateRedemptionEpoch {
    type ArrangedAccounts = UpdateRedemptionEpochInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let key = next_account(&mut iter)?;
        let profile = next_account(&mut iter)?;
        let config = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(UpdateRedemptionEpochInstructionAccounts {
            key,
            profile,
            config,
            remaining: remaining.to_vec(),
        })
    }
}
