//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::borsh;
use carbon_core::deserialize::CarbonDeserialize;
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct RevokeLockPrivilegeEventEvent {
    pub locker: Pubkey,
    pub program_id: Pubkey,
    pub timestamp: i64,
}

impl RevokeLockPrivilegeEventEvent {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 16 {
            return None;
        }
        let discriminator = &data[0..16];
        if discriminator
            != &[
                228, 69, 165, 46, 81, 203, 154, 29, 82, 101, 118, 111, 107, 101, 76, 111,
            ]
        {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[16..];

        Self::deserialize(data_slice)
    }
}
