//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::borsh;
use carbon_core::deserialize::CarbonDeserialize;
use solana_pubkey::Pubkey;

/// PDA containing one account that can modify an Points type

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct PointsModifier {
    /// The data version of this account.
    pub version: u8,
    /// point_category
    pub point_category: Pubkey,
    /// can_increment
    pub can_increment: u8,
    /// can_decrement
    pub can_decrement: u8,
}

impl PointsModifier {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[191, 227, 217, 178, 58, 205, 44, 39] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}
