//! This code was AUTOGENERATED using the Codama library.
pub mod cargo_pod_row;
pub mod cargo_stats_definition_row;
pub mod cargo_type_row;

pub use self::cargo_pod_row::*;
pub use self::cargo_stats_definition_row::*;
pub use self::cargo_type_row::*;

use super::CargoAccount;

pub struct CargoAccountsMigration;

impl sqlx_migrator::Migration<sqlx::Postgres> for CargoAccountsMigration {
    fn app(&self) -> &str {
        "cargo"
    }

    fn name(&self) -> &str {
        "cargo_accounts"
    }

    fn operations(&self) -> Vec<Box<dyn sqlx_migrator::Operation<sqlx::Postgres>>> {
        vec![
            Box::new(CargoPodMigrationOperation),
            Box::new(CargoStatsDefinitionMigrationOperation),
            Box::new(CargoTypeMigrationOperation),
        ]
    }

    fn parents(&self) -> Vec<Box<dyn sqlx_migrator::Migration<sqlx::Postgres>>> {
        vec![]
    }
}

pub struct CargoAccountWithMetadata(pub CargoAccount, pub carbon_core::account::AccountMetadata);

impl From<(CargoAccount, carbon_core::account::AccountMetadata)> for CargoAccountWithMetadata {
    fn from(value: (CargoAccount, carbon_core::account::AccountMetadata)) -> Self {
        CargoAccountWithMetadata(value.0, value.1)
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for CargoAccountWithMetadata {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        let CargoAccountWithMetadata(account, metadata) = self;

        match account {
            CargoAccount::CargoPod(account) => {
                let row =
                    cargo_pod_row::CargoPodRow::from_parts(*account.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            CargoAccount::CargoStatsDefinition(account) => {
                let row = cargo_stats_definition_row::CargoStatsDefinitionRow::from_parts(
                    *account.clone(),
                    metadata.clone(),
                );
                row.insert(pool).await?;
                Ok(())
            }
            CargoAccount::CargoType(account) => {
                let row =
                    cargo_type_row::CargoTypeRow::from_parts(*account.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
        }
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for CargoAccountWithMetadata {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        let CargoAccountWithMetadata(account, metadata) = self;
        match account {
            CargoAccount::CargoPod(account) => {
                let row =
                    cargo_pod_row::CargoPodRow::from_parts(*account.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            CargoAccount::CargoStatsDefinition(account) => {
                let row = cargo_stats_definition_row::CargoStatsDefinitionRow::from_parts(
                    *account.clone(),
                    metadata.clone(),
                );
                row.upsert(pool).await?;
                Ok(())
            }
            CargoAccount::CargoType(account) => {
                let row =
                    cargo_type_row::CargoTypeRow::from_parts(*account.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
        }
    }
}
