name: CI
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [synchronize, opened, reopened]

env:
  CARGO_TERM_COLOR: always
defaults:
  run:
    shell: bash

jobs:
  ci:
    runs-on: warp-ubuntu-latest-x64-4x

    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-provider: warpbuild

      - name: Install Just
        run: cargo install just || echo "just already installed"

      - name: Install Carbon CLI
        run: cargo install --git https://github.com/sevenlabs-hq/carbon.git carbon-cli || echo "carbon-cli already installed"

      - name: Check required tools
        run: ./scripts/check-tools.sh

      - name: Run CI script
        run: ./scripts/ci.sh
