name: CI
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [synchronize, opened, reopened]

env:
  CARGO_TERM_COLOR: always
defaults:
  run:
    shell: bash

jobs:
  ci:
    runs-on: warp-ubuntu-latest-x64-4x

    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-provider: warpbuild

      - uses: taiki-e/install-action
        with:
          tool: just,carbon-cli

      - name: Run CI script
        run: ./scripts/ci.sh
